### ISSUE TITLE
Update langs

### ISSUE THREAD

**Issue by Adaptivity** [chylex/Hardcore-Ender-Expansion#103]
Language files in repo outdated(Russian language for example), plus http://hee-translate.chylex.com/ have no new strings which are in the current en_US.lang.
Also, https://github.com/chylex/Hardcore-Ender-Expansion/blob/ad3c4d6dc320fc2ee6f45fe1dbb506f094c299eb/src/main/java/chylex/hee/mechanics/compendium/events/CompendiumEventsClient.java#L111 move this string into .lang file.

**Comment by chylex** [comment]
Done, will update the language files before I release the update.

**Comment by Adaptivity** [comment]
Also, can you give text for these tooltips "item.charm.witcherydefense.tooltip", "item.charm.voidrescue.tooltip"? Or just delete them?

**Comment by chylex** [comment]
There's no text for them intentionally.

**Comment by Adaptivity** [comment]
I mean if these strings do nothing, can you remove them from http://hee-translate.chylex.com/ and from .lang files?

**Comment by chylex** [comment]
I could, but why?

**Comment by Adaptivity** [comment]
Because they are empty and if you remove them I can complete translation on 100% :D Since I can't translate empty space I can't complete translation on 100%, isn't this right?

**Comment by chylex** [comment]
Well, I removed them but they will return next time I update the files.
