### ISSUE TITLE
Localize version checker

### ISSUE THREAD

**Issue by Adaptivity** [chylex/Hardcore-Ender-Expansion#104]
https://github.com/chylex/Hardcore-Ender-Expansion/blob/6afa64be0b6b0605f3b70f1272b0fba0cacb69a6/src/main/java/chylex/hee/system/update/UpdateThread.java#L89-L114 more localization stuff

**Comment by chylex** [comment]
Yea, there's a ton of text to localize, I'll get on it.

**Comment by chylex** [comment]
I externalized a bunch of strings and updated the translation website. I can't do the update checker though, because that runs on server side, so it'd have to be mostly rewritten - there is a server translation system, but it doesn't work with the way I have the messages set up.

**Comment by Adaptivity** [comment]
So, do you plan to rewrite version checker at least in 1.8? Also, I noticed that you are using I18n format for localization, you better should switch to statcollector.translatetolocal because in some cases i18n can crash client (I saw that Ivorius have done this in psychedelicraft because of crashes)

**Comment by chylex** [comment]
I18n will only crash if it's called on server side. I'll check to make sure it's only called there. Not sure about updating the checker, I have more important features to work on that will probably take too much time on their own, so I'll handle the checker later.
