### ISSUE TITLE
[INVALID] Potion of instability crash

### ISSUE THREAD

**Issue by coolsquid** [chylex/Hardcore-Ender-Expansion#105]
Throwing a splash potion of instability crashed the game, and now it crashes whenever I open the world. Running HEE 1.7.1 and Forge 10.13.2.1291.

FML log: https://gist.github.com/coolsquid/a1ce368a306d4c4f0974
Crash report: https://gist.github.com/coolsquid/2d60d57b0381b5dcd145
Mod list: https://gist.github.com/coolsquid/f30190c14d8626457971

**Comment by chylex** [comment]
Removing vanilla potions is not supported.
