### ISSUE TITLE
[Feature Request] Instability Orb Whitelist / Blacklist

### ISSUE THREAD

**Issue by Brycey92** [chylex/Hardcore-Ender-Expansion#108]
I propose a configurable white/black list for items the instability orb spawns. Currently, it frequently spawns items that would otherwise have taken weeks of work to get, or banned items on my server. Ideally, this black/white list would use string ids instead of numerical ids.

**Comment by chylex** [comment]
If you remove recipes for and with banned items, they will stop appearing. Other than that, I can add an IMC message for the blacklist in next version.

**Comment by Brycey92** [comment]
I have used MineTweaker to remove all banned items' recipes, but many still appear from the instability orb. Is there some other way of removing the recipes so the orb doesn't drop them?

**Comment by chylex** [comment]
The orb only spawns items that are in crafting recipes, smelting recipes and biomes. If it still spawns, it's in one of those categories.

**Comment by Brycey92** [comment]
Oh, so I would also have to remove all recipes that use the banned items.

**Comment by chylex** [comment]
Implemented a blacklist.
