### ISSUE TITLE
very odd crash with ars magica

### ISSUE THREAD

**Issue by banjomarx** [chylex/Hardcore-Ender-Expansion#109]
http://pastebin.com/sHGWXzzu
im going to link the ars dev here too if possible so he can look. All i know is my server kept going down due to this

**Comment by banjomarx** [comment]
doing a little cross referencing for link purposes
https://github.com/Mithion/ArsMagica2/issues/1139

**Comment by banjomarx** [comment]
at first glance might not make sense why im posting this here but look at line 47 and down, seems to be endereye doing it

**Comment by chylex** [comment]
Already seen something like this, had to add a workaround to not call an update event. This one doesn't point to any HEE code, and AM2 is hasn't got publicly available source so there's nothing for me to fix.

**Comment by chylex** [comment]
Also I noticed you're using cauldron, neither HEE nor AM2 support it so you will probably not get any support there unless you can replicate the issue without it.

**Comment by Xanarios** [comment]
If it helps, I have recreated this error using strictly AM2 1.4.0.008 / HEE 1.8.1 / NEI (and library dependencies) under Forge 10.13.3.1389.  Seems to be related to the onLivingUpdates on the Ender Eye entity (chylex.hee.entity.boss.EntityMiniBossEnderEye).  Traces to a NPE somewhere in AM2's extended properties (am2.playerextensions.ExtendedProperties.getMaxMana).

Steps to reproduce from a fresh install are as follows:

1) Create new world
2) Create minimal end portal
3) Fly around for a little while until crash.

Crash Report: http://pastebin.com/WAzxV5qQ 
Full Error Log: https://www.mediafire.com/?012k6rtodffne9f

Cross Referencing Back to https://github.com/Mithion/ArsMagica2/issues/1139

**Comment by chylex** [comment]
Can't do anything about it. If AM2 devs think it's an error in HEE, they should start a new issue and describe why it's happening. AM2 has no public source and I'm not going to decompile it.

**Comment by chylex** [comment]
With help of Wastl2, we found another workaround for AM2 being silly, which should fix the crashes. It may cause other sort of issues, but once the next update is out (release 1.8.1, not the current beta), AM2 will have that workaround and will be officially marked as unsupported in crash reports.
