### ISSUE TITLE
The world may have leaked

### ISSUE THREAD

**Issue by Redlotus99** [chylex/Hardcore-Ender-Expansion#110]
I keep getting this error since I created my new modpack and enable HEE. When I remove the mod the message that the world may have leaked goes away. I have removed all mods and added them back one at a time and upon doing so it seems to only occur with HEE enabled. I have not however tried to use HEE only.  I am not using Cauldron any more so it could possibly be a mod conflict, Forge or HEE.

Any help with this would be great.

You can view the log here: 

https://gist.githubusercontent.com/Redlotus99/8735f0778fa6797362a5/raw/gistfile1.txt

Link to a cross-reference ticket with this issue to Forge:

https://github.com/MinecraftForge/MinecraftForge/issues/1803

Forge 1370
MC 1.7.10
HEE 1.8

**Comment by chylex** [comment]
It would help to just try HEE alone, I'm not sure what exactly is reporting world leakage but the only thing I added in 1.8 that I think could affect it is a dragon chunkloader. That however doesn't run if the dimension is unloaded and there are no players in it.

**Comment by Redlotus99** [comment]
Sure I will try that tomorrow. I'm by no means blaming HEE, just found it odd. I'll let you know the results.

**Comment by chylex** [comment]
Also, did it start happening in HEE 1.8 only or do you have the same issue with older version?

**Comment by Redlotus99** [comment]
I will check both shortly

**Comment by Redlotus99** [comment]
I did some pretty heavy testing. I can confirm the following:

With all mods enabled this occurs with HEE 1.8 and 1.7.1
With only HEE enabled this occurs with HEE 1.8, but does not occur with 1.7.1.

I will add one mod at a time back to the pack with 1.7.1 and see what causes the leak to start occurring and post back my results. As stated with HEE 1.8, it occurs with only Forge 1370 and HEE 1.8 in place.

**Comment by chylex** [comment]
Sounds like chunkloaders cause the leaking. I'll see if I can replicate it myself, and try to figure it out.

**Comment by Redlotus99** [comment]
Also wanted to list my steps in producing the error.

1. I deleted my world folder so I could test this on a clean world.
2. I enabled HEE 1.8 only.
3. Started the server and the error occurs.

For 1.7 I followed the same steps as above.  

I find it odd that it occurs with HEE 1.8 **AND** 1.7.1 with all mods enabled, but not in 1.7.1 with only HEE enabled.

**Comment by chylex** [comment]
I suspect it is the dragon chunkloader, which runs when the dimension is loaded, but it takes a little bit of time to shut off. I will try adding a check, however I don't know why it would leak the world with other mods, unless they are force-loading the dimension.

**Comment by Redlotus99** [comment]
If you want I can do more testing and slowly add one mod at a time and see if I can determine what mod is possibly force loading the dimension.

**Comment by chylex** [comment]
That's not something I can fix though, so you would have to report it to whichever mod is causing it.

**Comment by Redlotus99** [comment]
Of course, I was hoping to help anyone else that may have this issue in the future and also give you some help in case this pops up again from someone else.

**Comment by Redlotus99** [comment]
After some testing. I have found that HEE 1.8 on a newly created world will give the leak error. If I restart the server leaving the world in place and HEE 1.8 enabled the error is no longer present.

Hopefully this helps some.

You can reproduce it by:

1. Start server with a new world with only HEE 1.8 and Forge 1370.
2. World leak occurs.
3. Stop server.
4. Start server.
5. World leak no longer occurs.

**Comment by Redlotus99** [comment]
The error persists with a restart and all mods in place.

**Comment by chylex** [comment]
Alright, thanks for the info. Does the error actually cause anything, like does it stop the server from shutting down normally or cause lag or something?

**Comment by Redlotus99** [comment]
I haven't really let it go long enough to find out to be honest, but I have had an issue like it before in a previous pack back in a few packs back.  It eventually caused a server crash.

**Comment by Redlotus99** [comment]
I left the server running overnight and I logged on for a bit to test things out and I don't see any noticeable lag. The only thing I do see is an excessive amount of message in the logs.  

Have you been able to produce the error with HEE 1,8 and Forge 1370? I am curious if this is just me. If it is not something you can reproduce I plan to:

1. Wipe the server completely 
2. Re-install Minecraft, Forge and HEE and see if the error persists.

If you can reproduce the error I will await a fix then:

1. Wipe the world.
2. Install the fixed HEE
3. Install one mod at a time and see if the leak occurs after each mod is installed.

**Comment by chylex** [comment]
I'm running Forge 1291, will update just to be sure though.
Currently when I start a server with no world, it will log this:

    Preparing spawn area: 98%
    Done (...)! For help, type "help" or "?"
    Unloading dimension 1

When loading an existing world, it does pretty much the same, except it will log that it's loading dimension 1 and then it unloads it just fine. Logging in doesn't trigger anything regarding the End. I will update Forge just to be certain and update with a new comment.

**Comment by Redlotus99** [comment]
Will do. I am presently enabling one mod at a time to determine if anything else might be causing it. I am enabling HEE last after all the others and will post what results I have.

**Comment by chylex** [comment]
Running 1374, still no reports of leaking worlds.

**Comment by Redlotus99** [comment]
Interesting....once I get through all these mods I'll post my results, then we can probably close this. I am leaning towards another mod being the issue.

**Comment by chylex** [comment]
I realized the message type is debug, so it wouldn't show up in the server console. However I checked the FML logs, and there's no leaking message after "Gathering id map for writing to world save World" or anywhere else.

**Comment by Redlotus99** [comment]
You can close this ticket if you want. I am getting the error within a handful of mods I just enabled. If you want to keep it up open until I pinpoint the mod for reference purposes feel free.

**Comment by chylex** [comment]
Try disabling AM2, it seems to be generating something in/using the End right before the leaking is reported.

**Comment by Redlotus99** [comment]
Yea I tried that first and it didn't help. I'm backing out a couple of mods that I enabled to find the exact culprit.

**Comment by Redlotus99** [comment]
Oddly whatever it is affects all worlds not just dim 1.

**Comment by Redlotus99** [comment]
About 99% sure its ChickenChunks....

**Comment by Redlotus99** [comment]
Seems there might be a few issues but I can verify it isn't HEE. I apologize for taking up so much of your time....removing ChickenChunks solved part of the issue. Something else is still causing the leak randomly....but its not consistent as of right now I have the server running without issue. Appreciate all the help we need more hands on devs like you.

**Comment by Oxosorrel** [comment]
I see you have thaumcraft. Your mod list is similar to my custom mod pack. I noticed that thaumcraft nodes in a dimension with no players currently in them start lagging like crazy (using opis to see their tick rate go up 10 fold for each node tile entity) and it causes my server to barf memory leak warnings as it slowly chewed up the server ram.

Two ways to fix: I put an MFR chunk loader with creative energy cell in the dim to keep it from unloading. It didn't always work, an keeping a dim loaded isn't ideal. 

 So I ultimately ended up pregenerating a huge section of the overworld with normal thaumcraft configs (to get nodes) an then turning off thaums node gen in thaumcrafts config. Then rebuild the nether and the end by deleting their dim folder (this time without nodes). Down side is, from now on any new overworld would be node free, but my players have a 10,000 block circle with more nodes than they need. Upside, nodes in unloaded dims leaking. 

This happened in all forge builds 1291-1370. 

Anzor has stopped 1.7.10 support so we won't get a fix for that until we move to 1.8. 

It may not be what you are having, but its worth a look if it is what you've got going on.

**Comment by Oxosorrel** [comment]
https://github.com/Azanor/thaumcraft/issues/1684 may be related.

**Comment by Redlotus99** [comment]
Im highly doubtful this is the issue. I think the issue that I am running into is multiple mods hitting a world file at the same time. Ars Magica 2 reaches out and touches all the worlds, Forge Essentials reached out and touches all the worlds and any other mods such as Minions or ChickenChunks that reach out and touch a world on initial startup and they all do so at the same time locking the world for a moment and causing the other mods to error. Right now I still get an error on a world that is not even used. 

On initial start up a dimension 53 was created but there is no Dim 53 in any of my cfg files. Come to find out it was created because the original Dim was being locked by other mods either saving a backup of the world or locking it for various other reasons. Minions locks files temporarily as does AM2 and ForgeEssentials Backup.  I turned backup off and apparently there is a setting in AM2 to turn off the initial cache power data which I have yet to try. AS in below it seems AM2 and Minions are locking a world file. Oddly Dim 53 is never created on a restart or even available or referenced.

[15:37:09] [Server thread/TRACE] [FML/]: Ars Magica 2 >> Saving all cached power data for DIM 1 to disk
[15:37:09] [Server thread/INFO] [FML/]: Unloading dimension 1
[15:37:09] [Server thread/INFO] [ForgeEssentials/]: Saving permissions...
[15:37:52] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save World
[15:37:52] [Server thread/INFO] [STDOUT/]: [atomicstryker.minions.common.MinionsCore:getMinionMap:352]: Minions: minionMapLock was hanging
[15:37:53] [Server thread/TRACE] [FML/]: Ars Magica 2 >> Saving all cached power data for DIM 53 to disk
[15:37:56] [Server thread/INFO] [FML/]: Unloading dimension 53
[15:37:58] [Server thread/DEBUG] [FML/]: The world 6313c72d (World) may have leaked: first encounter (5 occurences).

[15:38:38] [Server thread/DEBUG] [FML/]: The world 711f7f79 (World) may have leaked: first encounter (5 occurences)..
