### ISSUE TITLE
Baby Enderman Steal when mobGriefing is false

### ISSUE THREAD

**Issue by RyelleZylar** [chylex/Hardcore-Ender-Expansion#111]
Title says it all. I think it's something that's been overlooked. One stole my Draconic Bow, and when I killed it, it didn't drop it. I turned mobGriefing off and keepInventory on for a reason...

**Comment by chylex** [comment]
Will be fixed; babies don't steal if you wear an Enderman Head, but they always drop the item they hold. If you also turn off mob drops, it might not work though.

**Comment by RyelleZylar** [comment]
I didn't know that about wearing the heads. Mob drops is on. I figured it would drop it when it died, but I tore apart the surrounding landscape with a magnet, and didn't get my bow back, so I don't know what happened.

**Comment by chylex** [comment]
Any mod that can modify mob drops?

**Comment by RyelleZylar** [comment]
I have no idea. I can post all the mods I have installed if it'll help. It's basically FTB Infinity with extras.

**Comment by chylex** [comment]
Not really, I don't know which mods could cause it.
