### ISSUE TITLE
Minetweaked recipes don't update in the Compendium

### ISSUE THREAD

**Issue by Dream-Master** [chylex/Hardcore-Ender-Expansion#112]
If i change Reipes via Minetweaker (some Recipes are to easy for me and my Pack) how i can display them in the Ender Compensium? In the lang file i can see only text.

**Comment by chylex** [comment]
There's no way currently, the Compendium loads the recipes dynamically but minetweaker runs too late so it changes the recipes after the Compendium registers them. I'll add another check to make sure tweaked recipes are detected properly, but it may also say they're modified to avoid crazy people from complaining about it to me.

**Comment by Dream-Master** [comment]
I will never complain about it because if I write the Recipes I know what i do. I make a ultra hardcore Mod and Tweak Server Project. So your Recipes will be get much much more expensive. Dont be worry I dont destroy Mod Balance I only want a better Integration of all the Mods I take in My Pack.
I have nearly 1 MB of Minetweaker Scripts so I change many things.
Only for the Players who want the play the Pack later(when i done with all Mods nerfing) it would be very nice if the Recipes be shown in the Compendium otherwise too many People asking why the Recipes in the Book are different than the Crafting Recipes.
If you scared about People want to complain about it, why you not send me a modified Version of HEE(if it is not to much work) so i not want to publish this Version it is only for my Beta Test Server with 4 People at the moment. (When the Pack is done i will asking every Mod Author for permission and maybe get the Pack to the Public.)
Or you make a config option for it to enable custom recipes load.

Thanks in advance

**Comment by chylex** [comment]
I'll figure something out and post an update when it's done.

**Comment by Dream-Master** [comment]
Nice thanks!

**Comment by chylex** [comment]
Implemented in 1.8.1 release that will come out soon. There is a question mark with tooltip next to removed or modified recipes, so people don't waste points for empty ones and don't get thrown off by modified ones, because the compendium is built so all related items are near each other, so that could be confusing.
