### ISSUE TITLE
Set harvestlevel for scorching pickaxe

### ISSUE THREAD

**Issue by Adaptivity** [chylex/Hardcore-Ender-Expansion#113]
Getting this message in log: [Client thread/ERROR] [IguanaTweaksTConstruct/IguanaTweaksTConstruct]: Could not set harvestlevel of item.scorchingPickaxe. Contact the Mod Author to properly support Item.setHarvestLevel(). 
should be easy to fix.

**Comment by chylex** [comment]
Can't support harvestLevel, the pickaxe has multiple of them that are handled automatically and won't work with anything that tries to change it. Any reason it's complaining?

**Comment by Adaptivity** [comment]
Ok, then. It's just a minor output in log.
