### ISSUE TITLE
[DUPLICATE] Ticking entity crash: Ender Eye boss.

### ISSUE THREAD

**Issue by InFerNos1** [chylex/Hardcore-Ender-Expansion#116]
Installed the mod, killed dragon, flew out a little ways, a tower with 4 spikes at the top generated in my view distance, crash. Crash log: http://pastebin.com/AkvGHM2X
Using the 1.8.1 beta.
*edit;
After reloading the game, I can head towards the tower, no issues then on.
*edit;
Just found at least 4 Ars Magica 2 red Flickers, I don't know anything about AM2 Flickers, or how they spawn, but they like this tower.
*edit;
Found another tower, crashed again when it rendered. Same log, only difference was the entity ID and entity name, the first being Ursa, the latter being Myva.

**Comment by chylex** [comment]
https://github.com/chylex/Hardcore-Ender-Expansion/issues/109#issuecomment-99422500
