### ISSUE TITLE
Crash with message "Expecting a stackmap frame" in "BlockEnderGoo.func"

### ISSUE THREAD

**Issue by trollusk** [chylex/Hardcore-Ender-Expansion#117]
Predictably crashes before reaching main menu.
Using:
HEE 1.7.10-1.8.1-beta
Forge 10.13.3.1403
A custom collection of mods

Crash report: http://pastebin.com/FrT4qWcF
Full log: http://pastebin.com/zshQkSWN

List of files in mods/ directory:

[1.7.2] ChickenShed (v1.1.3).jar
[1.7.10] Trapcraft - v2.3.0a.zip
[1.7.10]FloatingRuins-universal-1.7.10.r02.jar
[1.7.10]StartingInventory-universal-1.7.10.r03.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
airbreathercore-1.0.0.jar
antiqueatlas-4.2.2-1.7.10.jar
AppleCore-mc1.7.10-1.1.0.jar
appliedenergistics2-rv2-stable-1.jar
ArchimedesShips-1.7.1.jar
Artifacts-1.1.1.jar
Automagy-1.7.10-0.23.jar
BattleTowers-1.7.10.jar
BetterFoliage-mc1.7-1.0.10.jar
BetterFps-1.0.0.jar
BetterStorage-1.7.10-0.12.0.124.jar
BiblioCraft[v1.10.2][MC1.7.10].jar
BiomesOPlenty-1.7.10-2.1.0.1189-universal.jar
Botania r1.6-187.jar
buildcraft-6.4.14.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
Chisel2-2.3.10.37.jar
CodeChickenCore-1.7.10-1.0.5.37-universal.jar
CoFHCore-[1.7.10]3.0.2-262.jar
CookieCore-1.7.10-1.3.1-7.jar
CoroUtil-1.1.1.jar
dimensional-anchor-59.0.2.jar
DimensionalDoors-2.2.5-test8.jar
DragonAPI 1.7.10 V6f.jar
DynamicLights-1.7.10.jar
Enchiridion 2-1.7.10-2.0.1.jar
ExpandedRedstone 1.7.10 V6a.jar
Extra Achievements 2.1.1.jar
extrautilities-1.2.4b.jar
Farseek-1.0.4.jar
fastcraft-1.21.jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
Flaxbeard'sSteamPower-1.7.10-0.28.7.jar
Forbidden Magic-1.7.10-0.562.jar
forestry_1.7.10-3.5.4.13.jar
Ganys End-1.9.0.jar
Ganys Nether-1.8.0.jar
Ganys Surface-1.11.0.jar
GardenStuff-1.7.10-1.6.1.jar
growthcraft-apples-1.7.10-2.1.0.jar
growthcraft-bamboo-1.7.10-2.1.0.jar
growthcraft-bees-1.7.10-2.1.0.jar
growthcraft-cellar-1.7.10-2.1.0a.jar
growthcraft-core-1.7.10-2.1.0a.jar
growthcraft-fishtrap-1.7.10-2.1.0a.jar
growthcraft-grapes-1.7.10-2.1.0.jar
growthcraft-hops-1.7.10-2.1.0.jar
growthcraft-rice-1.7.10-2.1.0a.jar
HardcoreDarkness-1.4.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.1-beta.jar
HungerOverhaul-1.7.10-beta.6.jar
IguanaTinkerTweaks-1.7.10-2.1.4.jar
immibis-core-59.1.1.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-152.jar
Jabba-1.2.1a_1.7.10.jar
magicbees-1.7.10-2.1.22.jar
Mantle-1.7.10-0.3.2.jar
Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
MoreOredict[1.7.10][1.0.1].jar
mystcraft-1.7.10-0.11.4.00.jar
neiaddons-mc1710-1.12.5.17.jar
NEIIntegration-MC1.7.10-1.0.7.jar
NetherOres-[1.7.10]2.3.0-12.jar
No-More-Recipe-Conflict-0.2.jar
NotEnoughItems-1.7.10-1.0.4.95-universal.jar
NotEnoughResources-1.7.10-0.1.0.95.jar
Oceancraft-1.4.1.jar
OpenBlocks-1.7.10-1.4.jar
OpenModsLib-1.7.10-0.7.jar
OpenModularTurrets-1.7.10-1.3.8-35.jar
OptiFine_1.7.10_HD_B7.jar
Pam's DesertCraft 1.7.10a.zip
Pam's HarvestCraft 1.7.10h.jar
pig-manure-1.0.1.jar
plantmegapack-4.15-1.7.10-1230.jar
ProjectRed-1.7.10-4.6.0.79-Base.jar
ProjectRed-1.7.10-4.6.0.79-Compat.jar
ProjectRed-1.7.10-4.6.0.79-Integration.jar
ProjectRed-1.7.10-4.6.0.79-Lighting.jar
ProjectRed-1.7.10-4.6.0.79-Mechanical_beta.jar
ProjectRed-1.7.10-4.6.0.79-World.jar
QuiverBow_1.7.10_b97.zip
Railcraft_1.7.10-9.5.0.0.jar
ReactorCraft 1.7.10 V6e.jar
RedstoneArsenal-[1.7.10]1.1.0-80.jar
Repose-1.2.2.jar
rftools-2.75.jar
roguelike-1.7.10-1.3.6.3.jar
RotaryCraft 1.7.10 V6f.jar
ruins_log.txt
Ruins-1.7.10.jar
ruins.txt
runicdungeons-1.1.1.jar
RWG-alpha-1.3.2.jar.zip
ShadersModCore-v2.3.28-mc1.7.10-f.jar
Simple Recipes 1.7.10-1.8.2.jar
SolarExpansion-Basic-1.6a.jar
SpecialAI-1.7.10-1.1.1.jar
StorageDrawers-1.7.10-1.4.6.jar
Streams-0.1.4.jar
supercraftingframe-1.7.10.3.jar
TConstruct-1.7.10-1.8.4a.jar
Technomancy - 0.10.j - 1.7.10.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumcraftneiplugin-1.7.10-1.7.jar
thaumichorizons-1.7.10-1.1.1.jar
ThaumicInfusion-4.jar
ThaumicTinkerer-2.5-1.7.10-164.jar
TheCampingMod_2.1f.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
TiCTooltips-mc1.7.10-1.2.3.jar
TooMuchTime-1.7.10-2.4.0.B3-universal.jar
TravellersGear-1.7.10-1.16.3.jar
ttCore-MC1.7.10-0.1.1-74.jar
twilightforest-1.7.10-2.3.5.jar
UndergroundBiomesConstructs-1.7.2-0.6h13.jar
UpdateCheckerMod-1.7.10.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
WAILAPlugins-MC1.7.10-0.0.1-14.jar
Wawla-1.2.1_1.7.10.jar
weaponmod-1.14.2.jar
Weather-2.3.7.jar
WildCaves3-0.4.3.7(1.7.10).jar
witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.6.jar

**Comment by chylex** [comment]
Either the latest Forge or a coremod modifies vanilla code critical for HEE to function.

**Comment by trollusk** [comment]
I figured it out - it was a problem with the Farseek library (required for Streams and Repose mods). Updating to Farseek version 1.0.8 solved the problem.
