### ISSUE TITLE
java.lang.ClassCastException: chylex.hee.tileentity.TileEntityCustomSpawner cannot be cast to net.minecraft.tileentity.TileEntityMobSpawner

### ISSUE THREAD

**Issue by jkroepke** [chylex/Hardcore-Ender-Expansion#118]
Hi!

i tried to catch a Spawner in The End into a SpiritBinder (from RandomThings). After rightclicking on it, i got a Crash.

http://pastebin.com/zE2ra34t

No idea, if its a HHE or a RandomThings Issue.

I use the lastest version of Forge and HHE (1.8.1).

**Comment by chylex** [comment]
Can't find the code in RandomThings github, but it looks like an issue on their side.

**Comment by jkroepke** [comment]
Hi, thank you for your fast answer. I have asked @lumien231 for the 1.7.10 sourcecode, currently he hosted only the version for 1.8 minecraft.

Reference: https://github.com/lumien231/Random-Things/issues/5

I have a question, again. What is the normal behavior in this case?

chylex.hee.tileentity.TileEntityCustomSpawner have to be casted to a net.minecraft.tileentity.TileEntityMobSpawner object or the SoulBinder has block this TileEntity, because it this not a normal MobSpawner?

**Comment by lumien231** [comment]
Yeah, i check whether the block is an instanceof BlockMobSpawner but don't check the te again.

**Comment by chylex** [comment]
Closing it then.
