### ISSUE TITLE
Possible Ticking Error

### ISSUE THREAD

**Issue by Baulthral** [chylex/Hardcore-Ender-Expansion#119]
Whenever I go into the end, I get a crash.  I don't even see anything, just crash.  I have AM2 installed and I tried updating to 1.8.1 but it still crashes me.  

Log: https://paste.ee/p/1SxfI

**Comment by chylex** [comment]
Neither HEE nor AM2 are mentioned in the stack trace. You might have corrupted config file for AsieTweaks.

**Comment by asiekierka** [comment]
Corrupt AsieTweaks config. Also, AsieTweaks is buggy - don't use it unless necessary - there is a reason I said it is unsupported.

**Comment by Baulthral** [comment]
I'm running Resonant Rise, and I even had Asie Tweaks disabled before all this because it was causing an issue with another mod.  Asie Lib is only there because its required for the statues mod and the launcher complains when I don't have it.  Asie Tweaks config file isn't even in the folder anymore.  Not sure what to do.
