### ISSUE TITLE
Crash upon going to The End

### ISSUE THREAD

**Issue by Baulthral** [chylex/Hardcore-Ender-Expansion#120]
Sorry to be so annoying with these.  I don't know how to read crash reports.  Whenever I go into the end I crash, I'm running Resonant Rise modpack.  I was told it was something with Asie Tweaks but I have that mod disabled.  I do have Asie Lib installed but only because the pack will not launch without it, says its required. 

Log:  https://paste.ee/p/l2Rg0

**Comment by chylex** [comment]
Nothing in the crash references HEE. Test with only HEE enabled and reopen if it keeps crashing.
