### ISSUE TITLE
Enderman head looks strange (no bottom or inside textures and wrong render when worn)

### ISSUE THREAD

**Issue by Ianaver** [chylex/Hardcore-Ender-Expansion#122]
![2015-06-06_23 46 36](https://cloud.githubusercontent.com/assets/8153290/8122353/7554c336-106d-11e5-8f4c-f677a7fa24bf.png)
![2015-06-06_23 46 23](https://cloud.githubusercontent.com/assets/8153290/8122355/77c36078-106d-11e5-9b24-8c63c7a1b45b.png)

MINI ME!

**Comment by chylex** [comment]
None of the vanilla skulls have bottom either, and as for the head stuck on your penis, you may have some weird equipment on :P

**Comment by Ianaver** [comment]
lol ok

**Comment by chylex** [comment]
They have a hole on the bottom, there is a different texture but it's not a priority to change the Enderman heads. I can't replicate the bottom head, you have a conflicting mod.

**Comment by Ianaver** [comment]
I was about to post this earlier so here it is:
![2015-06-11_23 11 39](https://cloud.githubusercontent.com/assets/8153290/8162445/186db08e-1332-11e5-8e11-6cced9794c64.png)

**Comment by Ianaver** [comment]
and that is a solid texture, no holes

**Comment by Ianaver** [comment]
yeah idk anymore, however if you want here is the mod list in its entirety that I know has the issue
![mods 2](https://cloud.githubusercontent.com/assets/8153290/8162814/8eae266e-1334-11e5-811d-9d83f3a0b678.PNG)

**Comment by chylex** [comment]
Yea, that's not how skulls/heads look in vanilla.

**Comment by Ianaver** [comment]
that is a vanilla head dude XD

**Comment by Ianaver** [comment]
here is all the proof you will ever need :P 

![2015-06-15_08 22 18](https://cloud.githubusercontent.com/assets/8153290/8163418/c3b45c86-1337-11e5-8e20-8c0baa27d93d.png)

**Comment by chylex** [comment]
http://i.imgur.com/8mMnifV.png

**Comment by Ianaver** [comment]
@chylex true, true.... but endermen are not skellies are they? :P

**Comment by chylex** [comment]
Well, I used the skeleton heads as a code base for mine :P no idea about your extra head, possibly anything that has special armor rendering.

**Comment by Ianaver** [comment]
hmm maybe TiC I guess? I will try that and see.

**Comment by chylex** [comment]
Any updates? I'm watching you.
![](http://i.imgur.com/lrFrM3k.png)

**Comment by Ianaver** [comment]
@chylex lol nice one!

**Comment by chylex** [comment]
Replicated the problem, it only happens during certain render states regarding equipment... or something... anyways, I'll fix it.
