### ISSUE TITLE
enderman heads in world gen

### ISSUE THREAD

**Issue by XBlackLeopardX** [chylex/Hardcore-Ender-Expansion#123]
While using this mod in my custom modpack for my friends and myself when i generated a world i noticed there being enderman heads in the world generation
http://prntscr.com/7if86m
http://prntscr.com/7if8da

here is a list of all mods in the pack (i did remove the mod thats why its not showing in the list)
http://prntscr.com/7if8j9

if you need me to get a log and see if i can reproduce it again just let me know
my friend also generated a world and had the same thing happen

**Comment by chylex** [comment]
HEE doesn't generate anything in the Overworld.

**Comment by XBlackLeopardX** [comment]
i know but being that the heads are from HEE i didnt know where else to report this

**Comment by XBlackLeopardX** [comment]
i know its a compatibility issue though just not sure where its stemming from

**Comment by chylex** [comment]
Remove batches of mods until it stops, narrow down the list and find the conflicting mod.

**Comment by XBlackLeopardX** [comment]
ok i just generated another world and noticed this this time 
http://prntscr.com/7ifq8l
obsidian blocks this is at the very least something with thaumcraft because this only happens in the thaumcraft magical woods biome ill go remove more though and see if there are other mods also causing it

**Comment by XBlackLeopardX** [comment]
ok this might not be a compatibility issue with HEE because i removed some mods and this time it generated with AE2 blocks instead of HEE blocks
http://prntscr.com/7ifw7r

**Comment by chylex** [comment]
Sounds like some mod is using integer IDs.

**Comment by XBlackLeopardX** [comment]
it was project red causing the issue im updating to the lastest since a new update came out today and will test it to see if its fixed

**Comment by XBlackLeopardX** [comment]
ok newer version of project red did indeed fix the issue
