### ISSUE TITLE
World Ending Crash when Stardust Ore broken with Tinkers Construct Pickaxe

### ISSUE THREAD

**Issue by MajorGeneralRelativity** [chylex/Hardcore-Ender-Expansion#124]
So, I have a bug that happens when I break stardust ore with a tinkers construct pickaxe, and then turn away. It prevents me from loading the world. I will attach all the error reports I can:
What happens on world load: 
http://pastebin.com/yDaex3WG Client Error log
http://pastebin.com/LdNm3Jpz Server Error log

I am playing on singleplayer, and it happened on two worlds I had. I tried deleting the End dimension on one of the worlds, but it still crashes on world load.

Attached below is a list of the mods and version numbers I have installed on both worlds:
http://pastebin.com/zF07ynMJ

Please let me know if I need to do anything else to help, I would like to get this resolved ASAP.

Any help would be much appreciated!

**Comment by chylex** [comment]
Successfully replicated, looking into the issue.

**Comment by chylex** [comment]
Uploading a fix, broken worlds will load fine.

**Comment by MajorGeneralRelativity** [comment]
Thanks for the extremely speedy help! Double Thumbs up
