### ISSUE TITLE
Broken recipe crash

### ISSUE THREAD

**Issue by idealjo** [chylex/Hardcore-Ender-Expansion#125]
http://paste.ubuntu.com/11784554/

**Comment by chylex** [comment]
What am I supposed to do with it?

**Comment by ate0ate** [comment]
Are you using agricraft by any chance, with weeds disabled?

**Comment by idealjo** [comment]
yes i did disabled weeds on agrigraft. 
I changed the config to delete broken recipe, crash solved

**Comment by ate0ate** [comment]
Yeah, that's what I had to do. I posted this on Agricraft's github a while back and unfortunately it has not been fixed as of the 1.4.0 update.
