### ISSUE TITLE
Dragon essence altar should keep items from despawning

### ISSUE THREAD

**Issue by kutschkem** [chylex/Hardcore-Ender-Expansion#129]
I just lost a bunch of expensive items when my game crashed while they were being repaired by the dragon essence altar. I would expect the altar to keep items from despawning.

**Comment by chylex** [comment]
Well, the game shouldn't crash in the first place... if something else crashed and the items despawned, I can't really control it because anything could have gone wrong. If HEE crashed, I need the report.

**Comment by kutschkem** [comment]
Ok, thanks for confirming. Btw the crash had nothing to do wth HEE, and the world state didn't change back to a point before I placed the items, hence my thought that the despawning was a HEE bug.

**Comment by chylex** [comment]
Inventory and chunk saving is separate, so you might have had the inventory saved without items but the world itself wasn't. Either way, closing as it's not a HEE bug.
