### ISSUE TITLE
Replaced blocks have no name in the block registry

### ISSUE THREAD

**Issue by mezz** [chylex/Hardcore-Ender-Expansion#133]
Here's the original issue sent to Forestry
https://github.com/ForestryMC/ForestryMC/issues/773

mezz:
> here's the flow: forestry gets the replaced vanilla block and then looks up the name to write it to the config (for creating a new config) crash
when it's the real vanilla ender egg, looking up the name works and it's happy

chylex:
> right, I'm checking the delegates now
yea:
[00:25:47] [Client thread/INFO] [HardcoreEnderExpansion]: Mine null
[00:25:47] [Client thread/INFO] [HardcoreEnderExpansion]: Vanilla minecraft:dragon_egg
so I'll have to replace the delegate, which means more AT because the field is final and there's no method for it
ooor, I could poke cpw|out and see if there's any way to properly replace blocks
ooh, the delegate is actually fine, it's just the setName method is never ran.. ooh

**Comment by mezz** [comment]
Related to https://github.com/MinecraftForge/MinecraftForge/pull/2076

**Comment by chylex** [comment]
Fixed in dev, the update will be out today or tomorrow.
