### ISSUE TITLE
OpenBlocks Graves not spawning in END with HEE installed

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#135]
Not sure if this is Openblocks related issue, or HEE, but when I have HEE installed and I die in the End, grave does not appear and items just pops down on the ground. Without HEE installed all the items are going correctly into the Grave.

Also special enchants that should let you keep inventory after death (like Soulbound or Reincarnation) not work in the End as well.

Tested with: HEE 1.8.3

**Comment by chylex** [comment]
I would suspect the void chest mechanics which effectively steal the drops, I also had another issue report with dragon breaking the graves, but this might have been a misunderstanding and the grave didn't actually spawn at all... not quite sure what to do about it right now.

**Comment by zHawky** [comment]
So if you telling about bugs then how about me;
Im installing Grimoire of Gaia along with HEE,
after wandering in the end, there no one mobs from GoG i've ever seen..
Prevent mobs from spawning config i make true or false.
(ps JasonMcRay use gravestone instead openblocks grave, they not glitchy)

**Comment by chylex** [comment]
How is that related to openblocks graves?

**Comment by zHawky** [comment]
Prevent from create new annoying issue, thats obvious, but i could make it if you want.

**Comment by chylex** [comment]
That's the point of github issues... one bug per issue. If you have more, they will be ignored.

**Comment by zHawky** [comment]
Ok i'm just wipe my comments and create own issue.

**Comment by chylex** [comment]
Considering that Void Chest will be removed in HEE 2 and it's not a major issue, I'm closing it as intentional. If you really, really want me to change how it works, reopen the issue.

**Comment by JasonMcRay** [comment]
Oo.. HEE2? Exciting :)

Anyway, its fine... On my side, modpack, i will concider it also as Intentional and Minor, so we can call this "resolved" :D

Thanks

**Comment by chylex** [comment]
Well, it will have more changes, not entirely sure if updating a modpack with HEE 1 would be a great idea :P End dimensions from vanilla/HEE 1 are incompatible, so they'll have to be deleted... for the start.

**Comment by rob5251** [comment]
Would be nice if graves could spawn from Open Blocks, even if it was a config option like hardcore death: true/false
