### ISSUE TITLE
HEE and another modded mobs

### ISSUE THREAD

**Issue by zHawky** [chylex/Hardcore-Ender-Expansion#136]
Installing Grimoire of Gaia along with HEE,
after wandering in the end, there no one mobs from GoG will spawn.
Prevent mobs from spawning config had been switched true or false.

**Comment by chylex** [comment]
Can you upload the config file?

**Comment by zHawky** [comment]
http://pastebin.com/Q06Y6LdB

**Comment by chylex** [comment]
Can't see an issue, Grimoire of Gaia seems to be doing something wrong, but they didn't publish the source.

**Comment by chylex** [comment]
Closing for now, if the GoG devs have any further information on why it might be happening, please send them here.
