### ISSUE TITLE
Angry Endermen in Overworld, but no other signs of Endermanpocalypse?

### ISSUE THREAD

**Issue by Plobby** [chylex/Hardcore-Ender-Expansion#139]
Recently, having just slain the Ender Dragon on a small private server with my friend yesterday, we have been experiencing Angry Endermen spawning in our base. I would have initially said this was the Endermanpocalypse. However, there has been no other things to indicate this. Time still continues to carry on as normal, aswell as sleeping still working (gamerule doDaylightCycle is also still set to true). No Ender Demon has spawned at the world spawn. I have also checked the End to no avail. Initially, the config did not have the "enableEndermanpocalypse" option, so I manually added it, set it to False and restarted the server. Still, this persists. It is in clumps of Angry Enderman at seemingly random intervals. About 30 will spawn inside our base, then stay there until they are all slain, before another bunch spawn. 

I have tried various things, such as manually spawning an Ender Demon to slay. However, when I do this, it appears to instantly despawn itself. I have checked the End and found nothing there either. I am unaware of what is going on at the moment, but having Enderman attack you in your base every 30 seconds is making the game incredibly annoying to play and almost not worth it.

I am using v1.8.3 for Minecraft 1.7.10.

Thanks.

**Comment by chylex** [comment]
Endermanpocalypse doesn't exist. Your friend might be a troll, look around for Death Flowers - they spawn Angry Endermen and can make a huge mess eventually.

**Comment by Plobby** [comment]
Ah, thank you. They had placed some in flower pots on tables because they "looked pretty". They have never used the mod before and had no idea they would do that. Nor did I, surprisingly. Never really looked at them.

Anyways, thats that solved. Thanks.

**Comment by chylex** [comment]
Oh shit, yea they're probably too pretty. Take the flowers and murder them immediately, they're really dangerous.
