### ISSUE TITLE
[FIXED 1.8.4] Hardcore Ender Expansion and Anti ID Conflict incompatibility 

### ISSUE THREAD

**Issue by Shykel** [chylex/Hardcore-Ender-Expansion#142]
Recently I've installed the mod Orespawn in my own personal modpack which made it crash just before reaching the title screen. I've managed to narrow it down to these two mods, they both work perfectly without one another however. 

I'm fully aware that you can disable other mods doing something to the End but it doesn't seem to do anything in this situation. I also installed a handy conflict detector mod to see what the problem is, turns out that if they're together, it makes HEE fight default Minecraft for the Biome ID for the end which is odd because there's no mention of Orespawn in it at all.

Here's the crash log:

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!
 
Time: 09/09/15 17:05
Description: Conflicting biomes forced game to crash:
 
code.elix_x.coremods.antiidconflict.managers.BiomesManager$BiomesIDConflictException: Conflict between biomes with same id caused game to crash.
Affected ids:
9 is asked by: Sky (net.minecraft.world.biome.BiomeGenEnd), Sky (chylex.hee.world.biome.BiomeGenHardcoreEnd)
 
        at code.elix_x.coremods.antiidconflict.managers.BiomesManager.crash(BiomesManager.java:207)
        at code.elix_x.coremods.antiidconflict.managers.BiomesManager.postinit(BiomesManager.java:53)
        at code.elix_x.coremods.antiidconflict.AntiIdConflictBase.postinit(AntiIdConflictBase.java:52)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
        at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
        at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
        at com.google.common.eventbus.EventBus.post(EventBus.java:275)
        at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
        at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
        at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
        at net.minecraft.client.Minecraft.func_71384_a(Unknown Source)
        at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
        at net.minecraft.client.main.Main.main(SourceFile:148)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
 
 
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
 
-- System Details --
Details:
        Minecraft Version: 1.7.10
        Operating System: Linux (amd64) version 3.13.0-37-generic
        Java Version: 1.8.0_60, Oracle Corporation
        Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 1335099552 bytes (1273 MB) / 2154299392 bytes (2054 MB) up to 3817865216 bytes (3641 MB)
        JVM Flags: 2 total; -Xmx4096m -XX:MaxPermSize=256m
        AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 128 mods loaded, 128 mods active
        States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
        UCHIJ   mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
        UCHIJ   FML{7.10.99.99} [Forge Mod Loader] (modpack.jar)
        UCHIJ   Forge{10.13.4.1448} [Minecraft Forge] (modpack.jar)
        UCHIJ   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar)
        UCHIJ   bettersleepingcore{1.0} [Better Sleeping Core] (minecraft.jar)
        UCHIJ   CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar)
        UCHIJ   MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar)
        UCHIJ   Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar)
        UCHIJ   NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar)
        UCHIJ   backpacks16840{3.0.4} [Backpacks!] (zz-backpacks 1.7.10 - 3.0.4.jar)
        UCHIJ   OpenModsCore{0.8} [OpenModsCore] (minecraft.jar)
        UCHIJ   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
        UCHIJ   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.8.0.jar)
        UCHIJ   lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar.zip)
        UCHI    antiidconflict{1.3.5} [Anti Id Conflict] (AntiIdConflict-LATEST-1.7.10.jar)
        UCHI    AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar)
        UCHI    appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar)
        UCHI    MovingWorld{1.7.10-ALPHA-0} [Moving World] (movingworld-1.7.10-BETA-1.jar)
        UCHI    ArchimedesShipsPlus{1.7.10-ALPHA-0} [Archimedes' Ships Plus] (archimedesshipsplus-1.7.10-1.7.12.jar)
        UCHI    Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar)
        UCHI    Artifacts{1.1.3} [Artifacts] (Artifacts-1.1.3.jar)
        UCHI    atum{0.6} [Atum] (Atum-1.7.10-0.6.60.jar)
        UCHI    betterrecords{1.7.10-1.1.9} [Better Records] (betterrecords-1.7.10-1.1.9.jar)
        UCHI    bettersleeping{1.7.10-0.10.0} [Better Sleeping] (BetterSleeping-1.7.10-0.10.0.jar)
        UCHI    BiblioCraft{1.10.4} [BiblioCraft] (BiblioCraft[v1.10.4][MC1.7.10].jar)
        UCHI    CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar)
        UCHI    ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar)
        UCHI    ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar)
        UCHI    BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar)
        UCHI    Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar)
        UCHI    Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar)
        UCHI    BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1282-universal.jar)
        UCHI    AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar)
        UCHI    BuildCraft|Core{7.0.22} [BuildCraft] (buildcraft-7.0.22.jar)
        UCHI    BuildCraft|Silicon{7.0.22} [BC Silicon] (buildcraft-7.0.22.jar)
        UCHI    BuildCraft|Transport{7.0.22} [BC Transport] (buildcraft-7.0.22.jar)
        UCHI    BuildCraft|Builders{7.0.22} [BC Builders] (buildcraft-7.0.22.jar)
        UCHI    BuildCraft|Robotics{7.0.22} [BC Robotics] (buildcraft-7.0.22.jar)
        UCHI    BuildCraft|Energy{7.0.22} [BC Energy] (buildcraft-7.0.22.jar)
        UCHI    BuildCraft|Factory{7.0.22} [BC Factory] (buildcraft-7.0.22.jar)
        UCHI    CarpentersBlocks{3.3.6} [Carpenter's Blocks] (Carpenter's Blocks v3.3.6 - MC 1.7.10.jar)
        UCHI    Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar)
        UCHI    Railcraft{9.7.0.0} [Railcraft] (Railcraft_1.7.10-9.7.0.0.jar)
        UCHI    TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar)
        UCHI    ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
        UCHI    chisel{2.5.0.43} [Chisel 2] (Chisel2-2.5.0.43.jar)
        UCHI    chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar)
        UCHI    CosmeticArmor{1.0.5} [Cosmetic Armor] (CosmeticArmor-1.7.10-1.0.5.B8-universal.jar)
        UCHI    DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar)
        UCHI    eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar)
        UCHI    Enchiridion{1.3} [Enchiridion] (Enchiridion 2-1.7.10-2.0.2a.jar)
        UCHI    Enchiridion2{2.0.2a} [Enchiridion 2] (Enchiridion 2-1.7.10-2.0.2a.jar)
        UCHI    endercore{1.7.10-0.1.0.23_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.23_beta.jar)
        UCHI    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
        UCHI    EnderIO{1.7.10-2.3.0.413_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.413_beta.jar)
        UCHI    EnderStorage{1.4.7.37} [EnderStorage] (EnderStorage-1.7.10-1.4.7.37-universal.jar)
        UCHI    enderutilities{0.4.1} [Ender Utilities] (enderutilities-1.7.10-0.4.1.jar)
        UCHI    extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar)
        UCHI    ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar)
        UCHI    FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar)
        UCHI    HardcoreEnderExpansion{1.8.3} [Hardcore Ender Expansion] (HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar)
        UCHI    Forestry{3.6.3.20} [Forestry for Minecraft] (forestry_1.7.10-3.6.3.20.jar)
        UCHI    fossil{1.7.10 Build 7.2.0} [Fossils and Archeology Revival] (Fossils_Archeology_Revival-1.7.10_Build-7.2.jar)
        UCHI    GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar)
        UCHI    GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar)
        UCHI    GraveStone{2.12.3} [GraveStone] (GraveStone-2.12.4.jar)
        UCHI    iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar)
        UCHI    Hats{4.0.1} [Hats] (Hats-4.0.1.jar)
        UCHI    InfernalMobs{1.5.9} [Infernal Mobs] (InfernalMobs-1.7.10.jar)
        UCHI    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar)
        UCHI    IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar)
        UCHI    journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar)
        UCHI    magicalcrops{1.7.2 - 0.1 ALPHA} [Magical Crops] (magicalcrops-1.7.10_0.1.jar)
        UCHI    TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar)
        UCHI    Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar)
        UCHI    MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar)
        UCHI    RadixCore{2.0.2} [RadixCore] (RadixCore-2.0.2-1.7.10-universal.jar)
        UCHI    MCA{5.0.6} [Minecraft Comes Alive] (MCA-5.0.6-1.7.10-universal.jar)
        UCHI    Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar)
        UCHI    MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar)
        UCHI    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    Mystcraft{0.12.3.00} [Mystcraft] (mystcraft-1.7.10-0.12.3.00.jar)
        UCHI    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar)
        UCHI    MobAmputation{4.0.1} [MobAmputation] (MobAmputation-4.0.1.jar)
        UCHI    MobDismemberment{4.0.0} [MobDismemberment] (MobDismemberment-4.0.0.jar)
        UCHI    Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar)
        UCHI    cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.8(1.7.10).jar)
        UCHI    NEIAddons{1.12.3.11} [NEI Addons] (neiaddons-mc1710-1.12.3.11.jar)
        UCHI    NEIAddons|Botany{1.12.3.11} [NEI Addons: Botany] (neiaddons-mc1710-1.12.3.11.jar)
        UCHI    NEIAddons|Forestry{1.12.3.11} [NEI Addons: Forestry] (neiaddons-mc1710-1.12.3.11.jar)
        UCHI    NEIAddons|CraftingTables{1.12.3.11} [NEI Addons: Crafting Tables] (neiaddons-mc1710-1.12.3.11.jar)
        UCHI    NEIAddons|ExNihilo{1.12.3.11} [NEI Addons: Ex Nihilo] (neiaddons-mc1710-1.12.3.11.jar)
        UCHI    NetherOres{1.7.10R2.3.0} [Nether Ores] (NetherOres-[1.7.10]2.3.0-12.jar)
        UCHI    OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar)
        UCHI    OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar)
        UCHI    OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip)
        UCHI    harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar)
        UCHI    PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar)
        UCHI    SpecialMobs{3.1.1} [Special Mobs] (SpecialMobs-1.7.10-3.1.1.jar)
        UCHI    TiCTooltips{1.2.3} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.3.jar)
        UCHI    TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar)
        UCHI    TravellersGear{1.16.5} [Traveller's Gear] (TravellersGear-1.7.10-1.16.5.jar)
        UCHI    UtilityMobs{3.1.1} [Utility Mobs] (UtilityMobs-1.7.10-3.1.1.jar)
        UCHI    WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar)
        UCHI    witchery{0.24.0} [Witchery] (witchery-1.7.10-0.24.0.jar)
        UCHI    worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar)
        UCHI    WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
        UCHI    WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
        UCHI    WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar)
        UCHI    McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
        UCHI    ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar)
        GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 346.82' Renderer: 'GeForce GTX 960/PCIe/SSE2'
        OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
        Class transformer null safety: all safe
        AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
        CoFHCore: -[1.7.10]3.0.3-303
        ThermalFoundation: -[1.7.10]1.2.0-102
        ThermalExpansion: -[1.7.10]4.0.3B1-218
        Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
        MineFactoryReloaded: -[1.7.10]2.8.0-104
        TConstruct Environment: Environment healthy.
        NetherOres: -[1.7.10]2.3.0-12
        EnderIO: Found the following problems with your installation: "Optifine is installed. This is NOT supported." This may have caused the error. Try reproducing the crash WITHOUT this/these mods before reporting it.
        Stencil buffer state: Function set: GL30, pool: forge, bits: 8
        Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.

**Comment by chylex** [comment]
Remove Anti ID Conflict mod.

**Comment by Shykel** [comment]
Wow thank you that worked! (after reinstalling) you really know your stuff, thanks a lot

**Comment by chylex** [comment]
I might release an update to fix the conflict, so you can keep using the mod.

**Comment by chylex** [comment]
Will be fixed in next update.
