### ISSUE TITLE
Items disapearing upon opening Compendium

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#144]
Ok. First I thorught it is just a graphical glitch, but after few tests it really is not a glitch. What is happening is that when players will put items into a crafting table (normal vanilla) and they open-up the Compendium via clicking on item in NEI (to see the recipe) and they exit the compendium, the items put into the crafting table are gone.

Tried restarting the client, checking the ground, the items are nowhere.

using HEE 1.8.3

**Comment by chylex** [comment]
Disable NEI integration in config, I'll release a bugfix as soon as I can.

**Comment by JasonMcRay** [comment]
Sorry, but I cant see the NEI Integration option in the HEE config...

**Comment by chylex** [comment]
http://hee-api.chylex.com/#imc-system

**Comment by chylex** [comment]
I'll try to release 1.8.4 on thursday, sorry for the delay, just a tiiiny bit lazy with my current update process.

**Comment by JasonMcRay** [comment]
No worries. I temporarily disabled the NEI Integration with HEE.

**Comment by chylex** [comment]
Fixed and changed NEI integration, it will now only open the Compendium if you press the Compendium key while hovering over items in NEI. Will release sometime today.
