### ISSUE TITLE
Decomposition

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#145]
i am trying to add certain items from GregTech to Decomposition Blacklist, but I am getting invalid item message in the console:
Invalid entry in Decomposition Blacklist, item not found: gregtech:gt.metatool.01

I tried to look-up the correct syntax, but was unable to.

Am i doing something wrong?
S:decompositionBlacklist=gregtech:gt.metatool.01,

I also noticed that it says the same thing for ExtraUtilities Unstable Ingot, which should be hardcoded (https://github.com/chylex/Hardcore-Ender-Expansion/blob/e65fa3df06c1fa852bd22817963a2ee90dfcdc65/src/main/java/chylex/hee/game/ConfigHandler.java#L114)

Thank you.

HEE:1.8.3

**Comment by chylex** [comment]
ExtraUtils apparently changed the name or something, I'll have to revisit it. The decomposition blacklist is deprecated, use IMC API instead.

**Comment by JasonMcRay** [comment]
I was looking at the ExU ingot name. But it is still the same
ExtraUtilities:unstableingot

In the IMC can I put oredictionary entry, or does it support only direct
item names? Also does it support wildcard values like
gregtech:gt.metatool.01:*

Also I think this should be hardcoded in some way, because all items in GT
which are crafted with some meta tool (not consumed upon use) are giving
the "dummy/blank crafting tool" item in decomposition.

**Comment by chylex** [comment]
Neither supports oredict, just game registry names. I didn't realize '.01' was a part of the name, thought it was metadata :P in that case, just leave the "damage" section off and it'll accept it as a damage/metadata wildcard.

**Comment by JasonMcRay** [comment]
Cool... It works. Also the ExU unstable ingot is no longer giving me an error in the logs (no idea what happened there then.)

I guess this can be closed, just a question before the closing. Is it possible to give same oredictionaried items after decompositions?

For example if I am about to decompose Steel Anvil from Railcraft (Crafted with 4 Steel Ingots + 3 Steel Blocks) I am getting the correct items, but they are from separate mod (not unifyied). So i get 1 Steel Ingot from Railcraft another from GregTech, and same with Blocks.

Do you think you could at least force the decomposer to just give one same type of the materials? Or maybe even better, would it be possible to support GT unification system (@Blood-Asp could provide some info about it)

Here is the Unification code from GT:
https://github.com/Blood-Asp/GT5-Unofficial/blob/7e0b4194ac6c5651fab4b24e4f30c447697e11ab/main/java/gregtech/api/util/GT_OreDictUnificator.java
https://github.com/Blood-Asp/GT5-Unofficial/blob/55c596b008807a7cb4b58422efd07636425be1e2/main/java/gregtech/api/GregTech_API.java#L171-L189

**Comment by Blood-Asp** [comment]
Should this really get GT unification support, https://github.com/Blood-Asp/GT5-Unofficial/blob/7e0b4194ac6c5651fab4b24e4f30c447697e11ab/main/java/gregtech/api/util/GT_OreDictUnificator.java#L129 is the right method. Insert any item, get the right unificated back.

If not, i can only recommend to pipe the items for unification trough an GT ItemPipe or any GT Machine like the buffer. These all unificate on input.

**Comment by chylex** [comment]
HEE 1 is feature-frozen at the moment, as for HEE 2 I haven't got around to work on the decomposition yet.

**Comment by JasonMcRay** [comment]
OK. I guess that concludes all of this in here. Thanks a lot @chylex for being so responsive and for great adventure-y mod :)
