### ISSUE TITLE
Ender Demon is not spawning

### ISSUE THREAD

**Issue by Michal321mm** [chylex/Hardcore-Ender-Expansion#146]
If i use Ender Demon's spawn egg he doesn't spawn name bar is for 5 sec enabled and gone,Ender Demon only for 2 sec and he gone too and why enderman relic, gone at new versions? I like this Ender Demon, plz fix spawn egg and we can add 3 ender island biomes: 
1.is with this dungeon 
2.normal biome 
3.Normal biome with enderman relic part. 
PLZ make this, i like this mod and Ender Demon.

**Comment by chylex** [comment]
Ender Demon was removed at least a year ago.

**Comment by Michal321mm** [comment]
Why ender demon got removed because what? He crash? Or something blocks ender demon? Say why removed.

**Comment by chylex** [comment]
HEE 1 isn't finished and won't ever be, stuff just gets removed occasionally.

**Comment by Michal321mm** [comment]
Say why plz

**Comment by Michal321mm** [comment]
He will repleaced with new mob? And new stuffwill be added?

**Comment by chylex** [comment]
HEE 1 is feature-frozen, as for HEE 2 I can't say.

**Comment by Michal321mm** [comment]
But in version 1.7.9 ender demon spawn by spawn egg but didn't spawn ln survival because no this old biome.

**Comment by chylex** [comment]
There's no 1.7.9.

**Comment by Michal321mm** [comment]
I wanted say 1.8.1

**Comment by Michal321mm** [comment]
In 1.8.1 relic avaible in new 1.8.2 - 1.8.4 no relic and demon off

**Comment by chylex** [comment]
It was not meant to be spawned for over a year.

**Comment by Michal321mm** [comment]
Maybe by switching files this will be fixed? i try and say will work or no

**Comment by chylex** [comment]
The demon is not supposed to work, end of story.
