### ISSUE TITLE
Conflicts with Malisis Doors/Malisis Core

### ISSUE THREAD

**Issue by Nateolocity** [chylex/Hardcore-Ender-Expansion#149]
I opened the following crash report with OpenEye and it said that the mods involved included the Malisis mods and Hardcore Ender Expansion. If you could take a look at it that'd be appreciated.

http://pastebin.com/K8JPmNdD

**Comment by chylex** [comment]
No idea what Malisis Doors is doing, but it looks like they're doing it wrong. Report to them first, if the dev thinks it's HEE's fault, send them a link to this issue and let them explain what's going on.

**Comment by Ordinastie** [comment]
It is indeed an issue on my side that will be fixed in the next update.
