### ISSUE TITLE
Description: Exception getting block type in world

### ISSUE THREAD

**Issue by Dyonovan** [chylex/Hardcore-Ender-Expansion#150]
http://pastebin.com/bWq5FyhB

Have a good day :) You can tell at me in IRC

**Comment by chylex** [comment]
Me blames vanilla structure code for being obfuscated and too annoying to figure out. Sorry, this has been a rare issue for about a year I guess, got no idea what's causing it, and it disappears when you reload the game. HEE 2 will have fully custom generators that won't have this issue.
