### ISSUE TITLE
Endergoo buckets destroyed when emptied

### ISSUE THREAD

**Issue by olagarde** [chylex/Hardcore-Ender-Expansion#151]
Possibly intentional(?)  ...  an endergoo bucket, leftclicked on a drum that can accept endergoo, will transfer the liquid but not return an empty bucket.  No server or client errors logged.  Can't find any mention of this in the onine/ingame docs, wiki(s), configs, etc, but I could just be missing it.  Doesn't happen with buckets of any other fluid I've tried (oil, lava, sludge, water, essence, xp, honey, etc), but does happen with endergoo filling EU drums, OB tanks, EIO tanks, etc.  Does not happen when emptying the bucket via a fluid transposer or when leftclicking on a non-inventory block (ie., dirt, stone, etc).

If intentional, could the docs be updated to say so?  If not, please patch to return the empty bucket?

Minecraft 1.7.10
HardcoreEnderExpansion 1.7.10 v1.8.4 ("Ender Goo")
ExtraUtilities 1.2.6 ("Drum")
OpenBlocks 1.7.10-1.3-snapshot-500 ("Tank")
EnderIO 1.7.10-2.2.8.381 ("Fluid Tank")
Thermal Expansion [1.7.10] 4.0.3B1-218 ("Portable Tank")
ExtraCells 1.7.10-2.2.8b21 ("Certus Quartz Tank")

**Comment by chylex** [comment]
Don't know why it's happening, the way I register the bucket and the fluid looks fine to me.

**Comment by chylex** [comment]
It should be fixed in the next version, which might be HEE 2 unless there are more issues in the current versions.
