### ISSUE TITLE
Dragon Essence Altar not upgradable with Blocks

### ISSUE THREAD

**Issue by Keridos** [chylex/Hardcore-Ender-Expansion#157]
I cannot get blocks into the white cornerpieces like the wiki sais I should be able to do. Tried with Iron, Emerald and Redstone blocks. Using HEE v1.8.4. Forge 10.13.4.1558

**Comment by chylex** [comment]
Perhaps read the part of the wiki that says it's over a year out of date. Use the in-game Compendium for information.

**Comment by Keridos** [comment]
You should maybe remove all the pages from the wiki OR state on every page that the wiki is horribly outdated.

BTW, I read the new stuff about enchanting the machines, but I did not see any hints to wether the ingredients for the enchants were correct. I have used several stacks of end Powder and different stuff and have not been able to find a single ingredient yet. The compendium mentions that the correct ingredients should leave more end powder intact but so far I have not seen any reconizable pattern yet.

**Comment by chylex** [comment]
Can't, it's against the rules of wikia. Ingredients unlock gradually or you can unlock them with Knowledge Points and they will show up in the GUI.
