### ISSUE TITLE
java.lang.RuntimeException: A defective recipe has crashed the game! error when starting the game.

### ISSUE THREAD

**Issue by levicc00123** [chylex/Hardcore-Ender-Expansion#158]
full log can be found at: https://gist.github.com/levicc00123/5288d8ce6b603208bcd2

I have the following mods installed:

* The Aether II
* Buildcraft
* Buildcraft Compat
* Chromaticraft
* DragonAPI
* Electricraft
* Ender IO
* Ewy's Workshop
* Extra Utilities
* Hardcore Ender Expension
* Project Red
* ProjctE
* Railcraft
* Reactorcraft
* Rotarycraft
* RUnic dungeons
* Twilight Forest
* Steve's Factory Manager
* Steve's Carts
* WAILA
* JABBA
* Storage Drawers
* And probably a few more I'm not thinking of.

**Comment by chylex** [comment]
Read.
