### ISSUE TITLE
[Question]Replace recipes in the Book with new one

### ISSUE THREAD

**Issue by Dream-Master** [chylex/Hardcore-Ender-Expansion#161]
I remember we talk before about to change some of your recipes and add back a harder variant of it.

I try it before with Minetweaker and the recipes works well but not displayed in the Book.
(Minetweaker load recipes to late for be in the Book)

Now i try replace the recipes in my Core Mod and it works (the recipes is changed) but i get the following error. 
```````
Could not find ItemStack 1xitem.altarNexus@0 when registering recipe from registry.
``````
![screenshot 2015-12-22 21 45 12](https://cloud.githubusercontent.com/assets/2970688/11965924/6d29a55e-a8f8-11e5-80b0-f0621da738c4.png)


![screenshot 2015-12-22 21 45 02](https://cloud.githubusercontent.com/assets/2970688/11965818/947a82be-a8f7-11e5-8332-0019d05e6ddd.png)

What i can do to display the new recipes?

I using Gt Code for the recipe replace.

here is the code in the Core Mod.
https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/23045fc7562ca7f2eb623b5eede1e390a794bc37

Most of the Core Mod is written by Namikon. So my Java knowledge isn't that big.

Thanks for help in advance.

**Comment by chylex** [comment]
The system doesn't support wildcards, you have to use damage value 0.

**Comment by Dream-Master** [comment]
Ah ok i will try it. Thanks.

**Comment by Dream-Master** [comment]
I try this but this not working too. 
````````
GT_ModHandler.addCraftingRecipe(GT_ModHandler.getModItem("HardcoreEnderExpansion", "altar_nexus", 1L, 0), tBitMask, new Object[]{"DED", "EDE", "DED", Character.valueOf('D'), new ItemStack(Items.diamond, 1), Character.valueOf('E'), new ItemStack(Items.ender_eye, 1),});

````

**Comment by chylex** [comment]
Hmm... do you have a build of the mod I can use for testing?

**Comment by Dream-Master** [comment]
Sure I will give you a link when  I be back home.

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8081/job/GT%20New%20Horizons%20-%20CoreMod/152/
Core mod

This Lib mod you need too:

**Comment by chylex** [comment]
I changed the detection code in HEE 2, so if it works with that, I'll just port it back to HEE 1. If not, I'll try to figure out what's going on. Just need some time to test everything.

**Comment by Dream-Master** [comment]
Thanks to look inside it.

**Comment by chylex** [comment]
Okay, I can't run it because gregtech freezes in PostInit and uses almost all CPU power.

**Comment by chylex** [comment]
I tested the new recipe checking with Minetweaker, it seems to work fine now. I'll backport the solution to HEE 1, so then you can use MT to replace the recipes (they are only resolved first time you look at them, so reloading the scripts will not work).

**Comment by Dream-Master** [comment]
Ok this sounds fine. Thanks. (But i guess only Shaped or Shapeless recipes will work not Gt machine recipes ?)

**Comment by chylex** [comment]
There's no support in the Compendium for custom layouts... I guess you could workaround it by replacing the recipe with one that uses an unobtainable item (like the question mark from HEE - item_special_effects:18) and give it a custom name that explains what to do.

**Comment by chylex** [comment]
Since you have a custom mod for this, you can add a custom fragment type, like https://github.com/chylex/Hardcore-Ender-Expansion/blob/1.7.10-v1.8.4/src/main/java/chylex/hee/mechanics/compendium/content/fragments/KnowledgeFragmentCrafting.java

and then take the obj from KnowledgeRegistrations and replace the fragment set (you will need to replace both fields, it's a bit hacky) https://github.com/chylex/Hardcore-Ender-Expansion/blob/1.7.10-v1.8.4/src/main/java/chylex/hee/mechanics/compendium/content/KnowledgeObject.java#L39-L40

**Comment by chylex** [comment]
Ported to the latest HEE 1 branch, it will be in the next update.

**Comment by Dream-Master** [comment]
Ok will try it and ask you if i have a question.

**Comment by Dream-Master** [comment]
When Version 1.8.5 will be release ?

**Comment by chylex** [comment]
http://hee.chylex.com/download

**Comment by Dream-Master** [comment]
:+1:
