### ISSUE TITLE
Ticking memory error?

### ISSUE THREAD

**Issue by scourge728** [chylex/Hardcore-Ender-Expansion#162]
So I'm making a PRIVATE modpack with this mod in it and when I go to the end I get this
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 12/23/15 6:37 PM
Description: Ticking memory connection

java.lang.NullPointerException: Ticking memory connection
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:101)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
Connection: net.minecraft.network.NetworkManager@191db4f0
Stacktrace:
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
Minecraft Version: 1.7.10
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_66, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1014027736 bytes (967 MB) / 2202525696 bytes (2100 MB) up to 3723231232 bytes (3550 MB)
JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:-OmitStackTraceInFastThrow -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xms512M -Xmx3584M -XX:MetaspaceSize=512M
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 44 mods loaded, 44 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCHIJAAAA mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar)
UCHIJAAAA Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar)
UCHIJAAAA CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar)
UCHIJAAAA NotEnoughItems{1.0.4.95} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.95-universal.jar)
UCHIJAAAA OpenModsCore{0.7.3} [OpenModsCore] (minecraft.jar)
UCHIJAAAA <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar)
UCHIJAAAA divinerpg{1.4.1.3} [DivineRPG] ([1.7.10][SMP]DivineRPG-1.4.1.3.jar)
UCHIJAAAA FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar)
UCHIJAAAA CoFHCore{1.7.10R3.0.0RC7} [CoFH Core] (CoFHCore-[1.7.10]3.0.0RC7-211.jar)
UCHIJAAAA IC2{2.2.746-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.746-experimental.jar)
UCHIJAAAA advancedgenetics{1.5.9} [Advanced Genetics] (advancedgenetics-1.7.10-1.5.9.jar)
UCHIJAAAA AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar)
UCHIJAAAA chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.0.jar)
UCHIJAAAA CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner 3.3.0.zip)
UCHIJAAAA MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip)
UCHIJAAAA endercore{1.7.10-0.0.1.13_alpha} [EnderCore] (EnderCore-1.7.10-0.0.1.13_alpha.jar)
UCHIJAAAA ExtraUtilities{1.2.8} [Extra Utilities] (extrautilities-1.2.8.jar)
UCHIJAAAA farlanders{1.2b} [The Farlanders] (farlanders-1.7.10-v1.2b.jar)
UCHIJAAAA FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar)
UCHIJAAAA flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar)
UCHIJAAAA iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar)
UCHIJAAAA GraviGun{4.0.0-beta} [GraviGun] (GravityGun-4.0.0-beta.jar)
UCHIJAAAA HardcoreEnderExpansion{1.8.4} [Hardcore Ender Expansion] (HardcoreEnderExpansion-MC-1.7.10-v1.8.4.jar)
UCHIJAAAA Hats{4.0.1} [Hats] (ichun-Hats-4.0.1.jar)
UCHIJAAAA IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar)
UCHIJAAAA Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar)
UCHIJAAAA JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar)
UCHIJAAAA journeymap{5.1.1} [JourneyMap] (journeymap-1.7.10-5.1.1-unlimited.jar)
UCHIJAAAA Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar)
UCHIJAAAA Morph{0.9.2} [Morph] (Morph-Beta-0.9.2.jar)
UCHIJAAAA Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar)
UCHIJAAAA neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar)
UCHIJAAAA NotEnoughCodecs{0.3} [NotEnoughCodecs] (NotEnoughCodecs-1.7.10-0.3.jar)
UCHIJAAAA notenoughkeys{@MOD_VERSION@} [NotEnoughKEys] (NotEnoughKeys-1.7.10-1.0.0b29.jar)
UCHIJAAAA OpenMods{0.7.3} [OpenMods] (OpenModsLib-1.7.10-0.7.3.jar)
UCHIJAAAA OpenBlocks{1.4.3} [OpenBlocks] (OpenBlocks-1.7.10-1.4.3.jar)
UCHIJAAAA fodc{1.6.1} [Ore Dictionary Converter] (OREDICTIONARYCONVERTER-1.6.1.jar)
UCHIJAAAA harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10k.jar)
UCHIJAAAA PortalGun{4.0.0-beta-6} [PortalGun] (PortalGun-4.0.0-beta-6.jar)
UCHIJAAAA simplyjetpacks{1.4.1} [Simply Jetpacks] (SIMPLYJETPACKS-MC1.7.10-1.4.1.jar)
UCHIJAAAA kitchen{1.3.17} [The Kitchen Mod] (TheKitchenMod-1.3.17-1.7.2-10.jar)
UCHIJAAAA WailaHarvestability{1.1.2} [Waila Harvestability] (WailaHarvestability-mc1.7.x-1.1.2.jar)
UCHIJAAAA wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-21.jar)
GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
Class transformer null safety: all safe
CoFHCore: -[1.7.10]3.0.0RC7-211
Mantle Environment: Environment healthy.
Stencil buffer state: Function set: GL30, pool: internal (hacked forge), bits: 8
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Player Count: 1 / 8; [EntityPlayerMP['scourge728'/8084, l='New World', x=100.00, y=49.00, z=0.00]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'

Of course I am using 1.7.10 version because it's in 1.7.10

**Comment by chylex** [comment]
Remove Chocolate Quest and try again.

**Comment by scourge728** [comment]
tested with out it and issue is gone thx will submit this to chocolate quest people
