### ISSUE TITLE
Crash relating to dragon eggs POSSIBLY caused by this mod

### ISSUE THREAD

**Issue by Sunconure11** [chylex/Hardcore-Ender-Expansion#163]
I have a structure in the overworld that spawns rarely in my modpack that has a dragon egg. However, when I try to obtain the egg using an iron sword, I get this crash:

http://pastebin.com/m8ViG1jw

**Comment by chylex** [comment]
Honestly I have no idea what happened, because the crash doesn't reference Hardcore Ender Expansion in any way. Can you try it on a vanilla server? Cauldron isn't supported.

**Comment by Sunconure11** [comment]
It turned out to be related to Dragon Mounts.

**Comment by Sunconure11** [comment]
Crash is likely a cauldron issue, unless LAN is not an optimal place to test things relating to servers.

**Comment by Sunconure11** [comment]
Left-clicking worked on getting the egg.

**Comment by Sunconure11** [comment]
I'll test things on a dedicated server to make sure HEE and Dragon Mounts are not having issues

**Comment by chylex** [comment]
Alright, sorry but it's not in my ability to support unofficial server software besides pure Forge. If you find what exactly is causing it, then I might be able to implement a fix, but right now the crash does not point to HEE so there likely isn't anything I can do.

**Comment by Sunconure11** [comment]
Issue is not related to Cauldron. I replicated it in a vanilla forge server. This might be something the Dragon Mounts dev would need to do though.

**Comment by Sunconure11** [comment]
I thought it was a conflict between these two mods, but, I think Dragon Mounts might just need to be ported to later versions of forge.
