### ISSUE TITLE
[COMPATIBILITY] An option to have an alternative way to move the dragon egg without using a sword

### ISSUE THREAD

**Issue by Sunconure11** [chylex/Hardcore-Ender-Expansion#164]
Right clicking on the dragon egg with dragon mounts causes it to begin hatching. Would it be possible to add an option that does not require right clicking on the egg in order to take it?

**Comment by chylex** [comment]
Not sure what changed, but HEE and Dragon Mounts have never been compatible.

**Comment by Sunconure11** [comment]
Nothing changed, but, I think having alternative ways of obtaining the egg without right-clicking could allow the two to be compatible.

**Comment by chylex** [comment]
Dragon Mounts used to crash when installed with HEE, so something definitely changed.

**Comment by chylex** [comment]
Hmm... you should be able to use left click to get the egg. If that doesn't work, add another comment and I'll backport a change from HEE 2, however considering you also had a crash with HEE and Dragon Mounts in another issue, I don't think the two mods will work very well.

**Comment by Sunconure11** [comment]
The issue happened on SMP. I'll see if its Cauldron for sure by creating a test server.

**Comment by Sunconure11** [comment]
If it crashes on a default server, then its an issue relating to servers.

**Comment by chylex** [comment]
That's the other issue, this one should work fine if you use left click instead of right click.

**Comment by Sunconure11** [comment]
Tested it on LAN, the crashing from Dragon Mounts MIGHT be a cauldron issue, but, LAN is probably not the best place to test it.

**Comment by chylex** [comment]
Use the other issue for crash information, this one is closed.
