### ISSUE TITLE
charms of slaughter impact cause player damage to other players bypassing pvp=off

### ISSUE THREAD

**Issue by ProsperCraft** [chylex/Hardcore-Ender-Expansion#166]
charms of slaughter impact hurt other players around the player using the charm bypassing pvp off.

**Comment by starky2kay13** [comment]
yeah i have tested this with all tiers off the charm and each tier causing more dmg also tested on doffrent packs .

**Comment by chylex** [comment]
Heh, can't actually remember whether this was an intended part of the design... might be there to make players more careful. It's a set amount of generic damage, it doesn't actually count as player damage (which is probably the reason why it doesn't respect the PVP flag). Not sure how to handle this.

**Comment by chylex** [comment]
Guess I'll set it to honor the PVP setting in the next bugfix update for HEE 1, HEE 2 will redesign everything anyways.
