### ISSUE TITLE
Instability Orb and items with removed recipes (minetweaker)

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#171]
Hi Chylex.

I know that there is a blacklist feature to disable items from being obtainable via Instability Orb, but... some items are still available. Mainly those with recipes removed via Minetweaker. I know for sure that they are not obtainable, i dont have any recipes for those items in my Modpack. They also do not spawn in any chests.

Is it a bug? Or something that you cannot handle and I will need to add a HUGE list of items into the blacklist manually?

HEE: 1.8.5 (1.7.10)
Modpack: InfiTech 2

**Comment by chylex** [comment]
Minetweaker runs too late, the recipes aren't removed at the point where HEE processes them and it would probably be too inefficient to reload the recipe list every time. Might be easier just to disable all items in the blacklist and have it use the chest generator instead.

**Comment by JasonMcRay** [comment]
If i will disable all can i then add some items back with whitelist?

**Comment by chylex** [comment]
Sorry, blacklist only.

**Comment by chylex** [comment]
The recipes reload once per world whenever the item is triggered.
