### ISSUE TITLE
[QUESTION] Compendium localization.

### ISSUE THREAD

**Issue by Ghostlyr** [chylex/Hardcore-Ender-Expansion#172]
Hello!
I would like to to know whether localization of **compendium** is carried out? If yes, where I could start working with it? I want to help with russian translation but on site found only main mod localization.
Excuse me if did not see somewhere information about that.

**Comment by chylex** [comment]
HEE 1 is frozen which means no more updates, and HEE 2 is work-in-progress so the Compendium does not have any texts as of now.
