### ISSUE TITLE
LIFE_STEAL charm conflicts with WITCHERY_HARM

### ISSUE THREAD

**Issue by Estella** [chylex/Hardcore-Ender-Expansion#173]
Hardcore-Ender-Expansion/src/main/java/chylex/hee/mechanics/charms/CharmType.java

if positional slots are ignored during crafting, it is not possible to make witchery charm with level 2 status effects, due to conflict with life steal's charm. 

LIFE_STEAL		    new CharmRecipe(29).rune(POWER).rune(VIGOR,2).rune(MAGIC).rune(VOID).prop("stealhealth",4).prop("stealdealt",16),

WITCHERY_HARM		new CharmRecipe(45).rune(POWER).rune(MAGIC).rune(VIGOR,2).rune(VOID).prop("badeffchance",0.09F).prop("badefflvl",2).prop("badefftime",5),

Found issue on The-1.7.10-Pack, v1.8.4 : HardcoreEnderExpansion  MC-1.7.10  v1.8.4.jar

**Comment by chylex** [comment]
Thanks for the report, I'll fix it in future versions. Unfortunately HEE 1 is frozen unless a major issue is found, so the fix may only be available for HEE 2 when it comes out.

**Comment by chylex** [comment]
There were quite a few oversights with the recipes, since I'm redesigning the mod I just fixed a couple broken ones and disabled two of the conflicting recipes with Life Steal and Witchery Harm.
