### ISSUE TITLE
Crash with Betweenlands

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#174]
https://gist.github.com/Zsashas/37ba3604feab4964afe3eee6d2b8d14a

**Comment by chylex** [comment]
Betweenlands is probably not registering one of their entities, that's the only reason I can think could cause the crash.

**Comment by Zsashas** [comment]
What integration is there with AM2, anyway? What would I be missing out on?

**Comment by chylex** [comment]
The integration works around an AM2 crash, but I think it was fixed in AM2 so it hopefully wouldn't crash (but AM2 aspects might not work on some of the HEE mobs).

**Comment by TheCyberBrick** [comment]
Yes, that could be the case. We accidentally removed an entity from the registry and that was fixed just recently (https://github.com/Angry-Pixel/The-Betweenlands/commit/9e8a6c50ca9d40300f28f3ab0f0ddbe65271da6c). I'll test it today if I have time.

**Comment by TheCyberBrick** [comment]
Just realized that it's this that's causing the error: https://github.com/Angry-Pixel/The-Betweenlands/blob/master/java/thebetweenlands/entities/properties/list/recruitment/EntityPropertiesRecruit.java#L42
I'll fix it later today.

**Comment by chylex** [comment]
Fixed on Betweenlands' side.
