### ISSUE TITLE
Was defective recipe may related to forestry?

### ISSUE THREAD

**Issue by lightning02** [chylex/Hardcore-Ender-Expansion#175]
http://pastebin.com/6MNp1CPy

I have read around that this crash is releted to biomes o plenty but this happen to me when i switch the old forestry mods with new ones (expecially adding binniepatcher 1.6).
i know this tipe of crash is "resolved" with Hardcore Ender Expansion 1.8.5 because the broken recipe remover is automatically set on enable but i used 1.8.4 in order to test this.
If i use 1.8.5 i lose the possibility to make some recipe? or, can i still use minetweaker in order to make a new recipe for the broken item? because if i don't lose any stuff with the broken recipe remover i'm just gonna update on HEE 1.8.5

**Comment by chylex** [comment]
You don't lose any recipes because the removed ones would not have worked in the first place, and need to be reported to the developer.

**Comment by lightning02** [comment]
so i can still find them (not functionally) actually in the game when i'm gonna play?

**Comment by chylex** [comment]
You can't, the recipes are broken so they don't have correct items.

**Comment by lightning02** [comment]
but are them shown in NEI?

**Comment by chylex** [comment]
No, the recipes are broken... it's impossible to show them correctly.

**Comment by lightning02** [comment]
you can't even bring the "crafted" item from creative mode, right?
if so, this seems a bad issue, what could we to in order to find out a solution?

**Comment by chylex** [comment]
You can, it doesn't remove the items.
