### ISSUE TITLE
Essence Altar infusion - difficulty dependant

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#176]
Hi. I know that issue tracker is not really the place to ask, but might you can see it as an enhancement if possible too.

I am currently adding via IMC messages some custom Dragon Essence Altar recipes. But what I would love to be able to do, is to set the amount of essence needed dependand on the difficulty. Like on Peacefull it will be 100, Easy 300, Normal 500, Hard 1000 for example. Would it be possible to do it? I am adding the IMC messages into my own custom mod.

Thank you

**Comment by chylex** [comment]
I guess you could make a custom build, there aren't going to be any more updates to HEE 1 unless there are major issues.

**Comment by JasonMcRay** [comment]
I was kinda hoping that you will say its already possible. I am just starting with modding and I must say that only thing I am able to do is add items and just basic stuff. I guess since the IMC for the Dragon Essence altar are running in postInit it will require rewriting quite a lot? I am not really confident on doing that.. :( Don't want to bother too much, but do you think you will be able to point me the correct direction? Thank you a lot

**Comment by chylex** [comment]
You will need to add a getCost method that takes difficulty level (EnumDifficultySetting I think) to
https://github.com/chylex/Hardcore-Ender-Expansion/blob/1.7.10-v1.8.5/src/main/java/chylex/hee/mechanics/essence/handler/dragon/AltarItemRecipe.java
and then replace .cost with .getCost(item.worldObj.difficultySetting) on
https://github.com/chylex/Hardcore-Ender-Expansion/blob/1.7.10-v1.8.5/src/main/java/chylex/hee/mechanics/essence/handler/DragonEssenceHandler.java#L248

Then you just add separate cost variables to AltarItemRecipe, add a constructor like
```
public AltarItemRecipe(ItemStack input, ItemStack output, int costPeaceful, int costEasy, int costNormal, int costHard){
```
and replace the recipes here
https://github.com/chylex/Hardcore-Ender-Expansion/blob/1.7.10-v1.8.5/src/main/java/chylex/hee/mechanics/essence/handler/DragonEssenceHandler.java#L33

Forget about IMCs, implementing support for those is a lot more difficult so just hardcode it.

**Comment by JasonMcRay** [comment]
Wooo... Really helpful. Will try to do it... Thanks a lot once again...

Also just to prevent any issues and have it clearly stated.... Do i have permission to redistribute the custom version of HEE within my modpack (InfiTech 2)?

**Comment by chylex** [comment]
Yea, feel free.
