### ISSUE TITLE
Wierd crash

### ISSUE THREAD

**Issue by axelpx** [chylex/Hardcore-Ender-Expansion#177]
Any ideas on this kind of server crash?

java.lang.NoSuchMethodError: net.minecraft.server.management.ServerConfigurationManager.func_72368_a(Lnet/minecraft/entity/player/EntityPlayerMP;IZ)Lnet/minecraft/entity/player/EntityPlayerMP;
at chylex.hee.system.util.DragonUtil.teleportToOverworld(DragonUtil.java:196)
at chylex.hee.entity.block.EntityBlockTempleDragonEgg.func_70071_h_
(EntityBlockTempleDragonEgg.java:87)

Full crashlog: http://pastebin.com/j0dDgWRJ

Hardcore Ender Expansion  v1.8.5
Server core: Thermos 1614.56

**Comment by chylex** [comment]
Cauldron is not supported, please reopen if you can replicate the issue on a pure Forge server. If it only happens on Cauldron, which is likely since I've not had any reports like this otherwise, then I can't fix it since Cauldron is missing features HEE requires to function.
