### ISSUE TITLE
Charms of defense and power do nothing

### ISSUE THREAD

**Issue by foulblade1** [chylex/Hardcore-Ender-Expansion#179]
Charm of Defense Do not work
Charm of power do not work

**Comment by foulblade1** [comment]
Charms of magic defense also do nothing
charm of equality do only half the effects no damage reduction or damage addition.
Charms of critical strike do not work either

**Comment by foulblade1** [comment]
v1.8.5 : HardcoreEnderExpansion

**Comment by foulblade1** [comment]
Never mind must be the multiplayer pack it works in single player

**Comment by chylex** [comment]
Maybe Cauldron or some plugin conflict, I think I had a report like that before.
