### ISSUE TITLE
Some compendium paging does not work

### ISSUE THREAD

**Issue by Ghostlyr** [chylex/Hardcore-Ender-Expansion#180]
Flipping some pages for some reason does not work... As i understand recipes just not provided to be placed on the same page, because by increasing the text (in the localization file) page-flipping works, but all the same recipes sometimes does not fit.
I remember that the old version development of abandoned, but I hope to fix, because due to which unable explore some items.

I have noticed problem with arcane shard and obsidian fragment, but there may be more.

![456465465645](https://cloud.githubusercontent.com/assets/8511068/15205479/716bf008-1839-11e6-8a2c-d8230c60b665.png)
![5a4acb75](https://cloud.githubusercontent.com/assets/8511068/15205480/736d2cc8-1839-11e6-8c1e-a9c24378c903.png)

Installed only last version HEE on mc 1.7.10 forge 1614

**Comment by foulblade1** [comment]
I can second this once you research the first curse the rest will not show up. They disappear from it completely

**Comment by chylex** [comment]
I'll look into it, thanks. There are a couple issues and feature requests piled up so I will make a minor update in a couple days.

**Comment by chylex** [comment]
Cannot replicate the issue, all 3 mentioned objects work fine. Please reopen with more details on how to replicate, it might be dependent on your Minecraft settings or mods.
