### ISSUE TITLE
Charms of defense and power do nothing with k cauldron multiplayer server

### ISSUE THREAD

**Issue by foulblade1** [chylex/Hardcore-Ender-Expansion#181]
Charms of power and defense do nothing on multiplayer server except make you weaker? What can cause this ?

**Comment by foulblade1** [comment]
Also i will donate some cash if you can fix this within a reasonable amount of time. Charms are hard to get and a big part of my pvp on my server.

**Comment by foulblade1** [comment]
Also the critical strike doesnt work or the magic armor penetration. Using latest version and latest version of kcauldron

**Comment by chylex** [comment]
Sorry, cauldron servers are not and will never be supported.

**Comment by foulblade1** [comment]
Ok thanks for the reply
