### ISSUE TITLE
More dying in the End causing compatibility issues

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#183]
Certain mods are adding enchantment called Soulbound (for example EnderIO) also possibly same would happen with Twilight Forest Charms of Keeping (that prevents item to be dropped on death), which makes the item kept on player when player dies. However in the end if player dies the soulbound item is not kept on death.

It would be ok if the items would drop on ground, but they just dissapear from player. Not in Void Chest, not on ground.

Tested multiple times.

Its pretty much similiar as in #135 with OB graves. But in there at least the items were dropped on ground.

**Comment by chylex** [comment]
Can you give me quick instructions on how to get soul bound for testing? Thanks.

**Comment by chylex** [comment]
Soulbound items go into the Void Chest, just tested it. Next update will fix event priority to let other mods handle it first, which should fix gravestones, charms of keeping, and whateverelse.
