### ISSUE TITLE
ArsMagica Integration NPE on ThermalDynamics Viaduct use

### ISSUE THREAD

**Issue by Leguan12** [chylex/Hardcore-Ender-Expansion#184]
Whenever one uses ThermalDynamics Viaducts with AM2 and HEE installed it causes a crash (NullPointerException) and temporary world-corruption (the player is still in the viaduct on world load and thus causes an insta-crash for the same reason)(removing either hee or am2 and loading the world once without them allows you to leave the viaduct and thus preventing the crash).
It seems that your am2 handler is being triggered when TD turns the PlayerModel and takes temporary control of the camera.
If my suspicion is correct a try-catch block in the am2NullWorldConstructionWorkaround method should either fix the issue or at least return a 'clean' crash report.

Full crashlog: https://gist.github.com/Leguan12/a208e17d8a7fd12a4620350b17dcf0af
(HEE, AM2 and TD on latest version)

**Comment by chylex** [comment]
Disable the AM2 workaround with the IMC option in HEE config.

HEE:System:DisableIntegration { "modid": "arsmagica2" }

**Comment by Leguan12** [comment]
It helped, thanks :+1: 
You're also right regarding TDs use of an Entity - The viaducts use a dummy entity wich the player is riding to make it seem like the player would in fact be inside the pipe.

**Comment by turtlelover73** [comment]
I'm having the same issue, but I can't figure out where to put the disable integration code to get it to actually work. Please let me know how to fix it.

**Comment by chylex** [comment]
http://hee-api.chylex.com/#basics

**Comment by turtlelover73** [comment]
I tried to follow that, but I think I messed up somewhere along the way. I have exactly this in my config
general {
    # List of IMC/API messages, documentation can be found on http://hee-api.chylex.com
    S:IMC< 
        Write your message here
        HEE:System:DisableIntegration 1.8.1 PostInit { "modid": "arsmagica2" }
     >
in that section, and the tubes still crash my game every time. Additionally, it generates a .errored config file every time I try, but the log doesn't show any errors when I looked through it. Sorry if I messed up something simple here.

**Comment by chylex** [comment]
You're not supposed to copy the entire table, just the command and JSON. If you don't delete _Write your message here_, HEE will ignore the config. You also have some corrupted character after S:IMC.

**Comment by chylex** [comment]
AM2 workaround will be removed next update.
