### ISSUE TITLE
Crash with BrassUtils

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#187]
https://gist.github.com/Zsashas/d68533f64dafecdac233e6ab8cb9a0ec

**Comment by chylex** [comment]
Nothing in the crash points to HEE being the cause, BrassUtils is spawning invalid items when a HEE mob dies from what I can tell. Reopen if BrassUtils dev says the problem is on HEE's side, but I doubt it.

**Comment by Zsashas** [comment]
Alright, I just figured I'd post it to both mods just in case.
