### ISSUE TITLE
[FIXED 1.8.6] Endermen Spawners

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#188]
In the Ender Eye towers, which have the ridiculous number of spawners, absolutely no Endermen spawn inside the first three floors. They all appear either on the floor just below the top (rarely), or, mostly, they spawn in midair above the Ender Eye (about 10 blocks up). Also, there appears to be no limit, causing the number of Endermen to rapidly reach FPS-impacting numbers.
![2016-06-17_18 42 59](https://cloud.githubusercontent.com/assets/6917535/16168481/ebbbc4ce-34bc-11e6-9715-f3e9dfbd786b.png)
![2016-06-17_18 50 41](https://cloud.githubusercontent.com/assets/6917535/16168482/ebbdd85e-34bc-11e6-9d92-6974e444a7b9.png)

**Comment by chylex** [comment]
Turns out I heavily messed up an old rewrite and offset all spawns 32 blocks higher, oops :/. Thanks for the report.

**Comment by Zsashas** [comment]
It did lead to some amazing Enderman Waterfalls, though.
