### ISSUE TITLE
[FIXED 1.8.6] Crash with Ars Magica & Ender Eye initial generation

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#189]
Was previously brought up, but Ars Magica wasn't open-source then, so there wasn't anything that could be done to really fix it. But maybe now, something better can be done.

Was supposedly fixed last year, but apparently not.

https://github.com/chylex/Hardcore-Ender-Expansion/issues/109

https://github.com/Mithion/ArsMagica2/issues/1530

**Comment by chylex** [comment]
Eh. If the AM2 dev tells me why it's crashing again.

**Comment by chylex** [comment]
Rewrote entity spawner to remove the need for the AM2 workaround.
