### ISSUE TITLE
[Request] [1.7.10] Config Option: Disable Ender Eye Towers

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#192]
Short-term fix for the compatibility issue with Ars Magica, or maybe just disable the spawning of the boss at the top of the towers. The swarms of Angry Endermen leave it enough of a challenge as it is.

**Comment by chylex** [comment]
Or AM2 could stop crashing.. I'll release a fix update eventually, HEE 1 is not developed anymore so no new features or major changes.

**Comment by chylex** [comment]
Fixed #189.
