### ISSUE TITLE
[Suggestion] Endstone types spread like grass

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#195]
You know what I mean, the "grass" types from the biome islands. They look like grass, why not have them spread like it? If this change was made, it would probably also be a good idea to make it so the types drop regular endstone, and you need silk touch to get the "grass" types. But that's not needed.

**Comment by chylex** [comment]
Won't do, sorry. It's unnecessary and probably won't make as much sense in context of HEE 2 which will not have biomes in the same way.

**Comment by LakMoore** [comment]
Nice idea Zsashas!  Sounds like Chylex has other plans for HEE2.  Can't wait to find out what they are.
