### ISSUE TITLE
No essence upon victory

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#196]
Isn't there supposed to be a shower of essence upon defeating the dragon the first time? The only things that dropped were exp, a yellow heart (Tinkers) and a shader bag (immersive engineering).

**Comment by chylex** [comment]
Try without any other mods, `/heeadmin kill-bosses` to quickly kill the dragon.

**Comment by Zsashas** [comment]
So this IS a bug, then. Now to figure out what mod causes it...

**Comment by chylex** [comment]
Read the /r/feedthebeast post, so I assume it's safe to close this since the conflict affects multiple mods and is not in HEE side.

**Comment by Zsashas** [comment]
No idea what happened, made a new world, tried killing the dragon several ways, dropped essence every time.

Must have been a one time thing, but still super annoying.

**Comment by Zsashas** [comment]
Now I am even more confused. I logged back into my regular world to test, in case it was a world-specific bug, and I found exactly two stacks of Dragon Essence in my inventory. I definitely didn't have that before, but I'm fairly sure I didn't cheat it in. I had logged out from the end, so I suppose it's possible that it was just invisible until now or something...but I swear I didn't have that essence before now. How much is the dragon supposed to drop? Exactly two stacks seems awfully convenient.

**Comment by chylex** [comment]
There's no exact number, it depends on how well you played and the difficulty level. 2 stacks is too little, the items fly off in all directions.

**Comment by Zsashas** [comment]
If I play on easy, and it took about an hour with a sword and bow, how much roughly SHOULD I have gotten?

**Comment by chylex** [comment]
Yea, but 2 stacks isn't enough anyways.

**Comment by Zsashas** [comment]
It's entirely possible it simply wouldn't all fit in my inventory. I'm going to try fighting the dragon again later in this same world...

**Comment by Zsashas** [comment]
Killing the dragon the second time for that world, on Easy this time, netted me exactly 1.5 stacks of dragon essence...

**Comment by chylex** [comment]
Hmm. Something may be messing with the drops, idk.
