### ISSUE TITLE
Adding items to Instability Orb blacklist via IMC in config file throws NPE if Natura is installed

### ISSUE THREAD

**Issue by Questwizard** [chylex/Hardcore-Ender-Expansion#197]
After seeing how game-breaking the Instability Orb was, I looked into the blacklist option. I added the following to the config file to try and blacklist everything:

HEE:Orb:ItemBlacklist {"pattern":{"id":"*"}}

The end result is the game crashing while processing the message, but only if Natura is installed. Even changing the above to only match a single item, like minecraft:stone for example, results in the same NPE crash if Natura is installed. Once Natura is removed, everything works as intended.

The message given is: java.lang.NullPointerException: Critical error handling post-load data.

A full log of the crash with only HEE, Mantle & Natura can be found here:
https://gist.github.com/Questwizard/95ac954c5d329d93b6661a0dc028523d

**Comment by chylex** [comment]
Instability Orb won't have this functionality in HEE 2, so I'm closing the issue.
