### ISSUE TITLE
Server crash while regenerating the End

### ISSUE THREAD

**Issue by Drobac** [chylex/Hardcore-Ender-Expansion#200]
After using the Dragon egg in the Temple to restore the End and the Dragon the entire server crashes. Afterwards if anyone tries to enter the End again, the server crashes again.
This is the crash log the server gave us:
https://gist.github.com/Dream-Master/d4d4da4091350a578839ab1c76ddcd08

If you need any extra data please ask

**Comment by Dream-Master** [comment]
Modpack we using :
https://github.com/GTNewHorizons/NewHorizons

HEE Version 1.86
Thermos Version 56

**Comment by chylex** [comment]
Cauldron is not supported, it changes code HEE requires to function properly. This specifically is a Cauldron error.
