### ISSUE TITLE
Charm crafting with shift-click does not take away runes

### ISSUE THREAD

**Issue by Ghostlyr** [chylex/Hardcore-Ender-Expansion#201]
![noname](https://cloud.githubusercontent.com/assets/8511068/19022589/4f17bafc-88fd-11e6-8006-55451cf31a7f.gif)

Mod version: 1.7.10 v1.8.6
Forge 1644

**Comment by chylex** [comment]
Known issue, HEE 1 is mostly discontinued to focus on HEE 2 so there will probably not be any more updates unless a bunch of bugs or critical crashes piles up again. I'll keep the issue open for now.

**Comment by chylex** [comment]
HEE 2 will not have Charms, so I'm closing the issue.
