### ISSUE TITLE
[Minor] Temple Caller cannot be shift-clicked into or out of inventories

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#202]
Tested with vanilla chests, ChromatiCraft loot chests, and TiCon backpack. Thought it was a bit odd, is all.

**Comment by Zsashas** [comment]
Just to add, attempting to shift-clicking one out of a vanilla double chest deleted it. Shiftclicking into the chest had no effect.

**Comment by chylex** [comment]
HEE 1 is discontinued, so I'm closing the issue.

**Comment by Shahelion** [comment]
I assume that means it also isn't relevant to HEE2, like the compass one? I guess with vanilla having a resurrection ritual now, that makes sense.

**Comment by chylex** [comment]
Correct, HEE 2 has its own way of dealing with giving anyone in multiplayer access to the Dragon (or any other part of the End for that matter).
