### ISSUE TITLE
Biome Compass is inaccurate

### ISSUE THREAD

**Issue by Zsashas** [chylex/Hardcore-Ender-Expansion#203]
Roughly 50% of the time, the biome is simply not there, just more void. Burning Mountains seem fairly reliable, but not the other two. Also, I have some existing ones marked on my atlas, and those don't have a biome square in the area when holding the compass. Even though the End has been reset three times now, it hasn't changed.

**Comment by chylex** [comment]
Yea, I know there are some issues with the compass, but it's unlikely to get fixed since HEE 1 is now discontinued unless there are serious bugs and crashes found, and the compass has been removed from HEE 2 completely.

**Comment by chylex** [comment]
HEE 1 is discontinued, so I'm closing the issue.
