### ISSUE TITLE
[1.8.6] Kicked from server with charms

### ISSUE THREAD

**Issue by JasonMcRay** [chylex/Hardcore-Ender-Expansion#204]
This happened on server, but possibly will happen also on SinglePlayer.

After HEE update to 1.8.6 one player was not able to log back on the server. This error was generated when player got kicked of the server: http://pastebin.com/baHPaiTh.

After deleting player data file, he was again able to log back in.

Worth noting that player had 4 charms: 3 in Charm Pouch and 1 in Voluminous pockets cloak (from Thaumic Tinkerer mod). I was able to remove the Pouch from players inventory using NBT Edit, but the Cloak was nowhere to be seen in the NBT editor. Not really sure what happened and who is at fault. But given that Thaumic Tinkerer is no longer maintained for couple of months, I am sorta hoping that you will be able to figure out the cause and have a hotfix.

Thank you very much.

**Comment by JasonMcRay** [comment]
Little bit more info about this. I have found exactly where the issue is. Players were crashing with Life Steal charm that had meta 29. But from the look of it (checking the source code) this charm has been probably removed in v1.8.6. So players who had the charm before the update started to crash because of that.

They had something in the charm pouch that was no longer supposed to exist, so that caused the crash.

**Comment by chylex** [comment]
I'll keep the issue open for HEE 2.

**Comment by chylex** [comment]
Charms will not be in HEE 2, so I'm closing the issue.
