### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by voidbreath** [chylex/Hardcore-Ender-Expansion#205]
Actually not sure how HEE got involved but there it is, server crashes on startup after trying to remove a chunk containing a tick exception.
Ticking entity crash report:
https://gist.github.com/voidbreath/69a95a4e831ccbfc833109742763c1b3

As a result of trying to fix:
https://gist.github.com/voidbreath/fc15592c70eefcc9924f5a1ff0af8aae

**Comment by chylex** [comment]
Your server jar file is corrupted, the original crash has nothing to do with HEE and the second crash is probably caused by accidentally removing a part of Minecraft that HEE uses.
