### ISSUE TITLE
CurrentModificationException while exploring The End

### ISSUE THREAD

**Issue by Eufranio** [chylex/Hardcore-Ender-Expansion#207]
When exploring The end, the server starts throwing a lot of CME's: http://hastebin.com/ocatevumih.md

**Comment by chylex** [comment]
You didn't specify the mod version, so I can only assume it's outdated. Update to latest.

**Comment by Eufranio** [comment]
Okay, I'm in latest: 1.7.10-1.8.6
Minecraft 1.7.10 and Forge 1614.
