### ISSUE TITLE
Animated Blocks (Stardust Ore)

### ISSUE THREAD

**Issue by Armigus** [chylex/Hardcore-Ender-Expansion#212]
While poking about the block textures and making John Smith image replacements I noticed that the stardust ore was 16 numbered images, presumably an animation of some kind.  Minecraft usually tiles animated cells vertically into a single image and makes a .mcmeta file describing the animation.

That was until I saw a few examples of the ore... they are randomly chosen from the list of images.  Interesting idea.  I may have to get more creative than normal to make the full set.

**Comment by chylex** [comment]
Closing as answered.
