### ISSUE TITLE
Crash with HEE

### ISSUE THREAD

**Issue by KorewaLidesu** [chylex/Hardcore-Ender-Expansion#213]
Here is the error recipe: [https://pastebin.com/EPuXtUdV](url)
Crash Post: https://pastebin.com/dTbDuU2Y
Hope the "overrideRemoveBrokenRecipes" work fine...
Sorry about the name... I can't change that... *quack*

**Comment by chylex** [comment]
Not a HEE issue, report it to the mods that add corrupted recipes.
