### ISSUE TITLE
Suspected causing of timing out in the end.

### ISSUE THREAD

**Issue by Nexus345** [chylex/Hardcore-Ender-Expansion#214]
This seems to be consistent with playing on a private server I have, and single player, but I can only see the problem on my server because of the console.
Unfortunately since the server times out instead of actually giving a crash log, I cannot send one. But here is how it goes down.
1.Someone enters the end.
2.We fight the dragon for a bit.
3.Entities stop moving.
4.Server times out, without leaving anything in the console-But "Failed generating WorldGenEndPowderOre at (coords), there might be an empty chunk." is usually one of the last things that is logged before timing out.

Instead of crashing, it just times out so again, no crash logs. I could send a startup log if needed.

note:We do have chocolate quest but I have tested and I am 99% sure chocolatequest is not behind this. I have removed it and also done the fixes but it seems that it is indeed hardcore ender.

Thanks for reading.

**Comment by Nexus345** [comment]
Sorry, 
Version is . 1.7.10 latest cauldron.
The forge version is 1.7.10-10.13.4.1614.

**Comment by chylex** [comment]
You didn't say if it happens without Cauldron and any other mods with the same world, but either way HEE 1 is discontinued and won't have any more updates.

**Comment by Nexus345** [comment]
Rip, thanks for the quick reply.
