### ISSUE TITLE
Ectoplasm obtaining

### ISSUE THREAD

**Issue by hohserg1** [chylex/Hardcore-Ender-Expansion#218]
Is it possible to get ectoplasm without amulet?
I play on the server and there is no way to get dragon essence and purefied amulet.

Ghost is real entity? May he be killed by some area attacks for drop ectoplasm?

**Comment by chylex** [comment]
I don't remember. If the compendium doesn't mention any alternatives, then no.

**Comment by hohserg1** [comment]
Thx for answer. 
It seems no other way for obtain ectoplasm(
Too many things tied to dragon and it hard in multipayer.
Try to make a second version of mod otherwise, please.

**Comment by Dream-Master** [comment]
@hohserg1 we add Quests in my pack you get ectoplasma. If you know how to use minetweaker you can make recipes too but not sure if this break balancing.

**Comment by hohserg1** [comment]
I play on not my server. However, I can ask admin for added recipe. But it are not sign that mod may have't multiplayer compability built-in

**Comment by chylex** [comment]
HEE 1 is discontinued and there will be no more updates, ever. HEE 2 is a complete redesign.

**Comment by hohserg1** [comment]
> HEE 2 is a complete redesign.

Yeah, I say about that

**Comment by MagmaSlime123** [comment]
> HEE 1 is discontinued and there will be no more updates, ever. HEE 2 is a complete redesign.

Well, give us a link or post it.

You never mentioned this anywhere.

**Comment by chylex** [comment]
Link to what? Literally the first paragraph on the official website states what I said here, and it has for years.
