### ISSUE TITLE
The "Bacon"

### ISSUE THREAD

**Issue by ZenSkylark** [chylex/Hardcore-Ender-Expansion#219]
Can somebody help me, is this a bug or in game because i can't understand what is bacon bacon bacon. Even in the other worlds..... The whole mod just almost literally changed. Ender Compendium into Bacon Compendium, Temple Caller into Bacon Caller, Adventures Diary into Bacon Diary, Dragon's Essence into Bacon Essence. I've searched everything in the website just to search this kind of Bug. Reply to the Owner Thx, I really like this mod but the bug is Major more likely corrupting the info.

If you need the Image, tell me.

**Comment by chylex** [comment]
Change `hardcoreEnderbaconMode` in configuration file to `2` (never enabled).

**Comment by ZenSkylark** [comment]
Thanks chylex, I did literally panic, in what going on. And its time to say byebye.
