### ISSUE TITLE
[Request] MineTweaker Support

### ISSUE THREAD

**Issue by UndeadZeratul** [chylex/Hardcore-Ender-Expansion#89]
I'm aware Modtweaker currently adds support, but @joshiejack has stopped working on it a while ago.  I don't know his policies on giving you the code to integrate it with HCEE, but I saw Blood Magic now has the classes from ModTweaker, and they're credited to Josh. [Here's](https://github.com/joshiejack/ModTweaker/tree/master/src/main/java/modtweaker/mods/hee) the classes you'd need to implement in order to get it working.

**Comment by chylex** [comment]
HEE has an API, if someone wants to make an addon to integrate it with whatever, they can. Not worth setting up everything just for one class.

**Comment by UndeadZeratul** [comment]
Fair enough, thanks.

**Comment by chylex** [comment]
Apparently someone's taking over modtweaker.

**Comment by UndeadZeratul** [comment]
oh?  If there's going to be continued support for it, that'll work.  Thanks for the head's up.
