### ISSUE TITLE
More than one enderdragon spawn when in peaceful

### ISSUE THREAD

**Issue by Ianaver** [chylex/Hardcore-Ender-Expansion#91]
from 1 dragon, now there are 500! (not really that many) however more than one appear over time

**Comment by chylex** [comment]
The center chunk is getting corrupted or re-generated by another mod or something. Need more info on how to replicate it.

**Comment by Ianaver** [comment]
all I did was go from normal to peaceful, and more than one started spawning, sometimes they disappear and then later reappear. sometimes at normal, the dragon doesn't show up for a long time and even it sometimes disappears too, If you wish to know the mods used I will attach a log file.

pastebin: http://pastebin.com/fnnXT1eY

**Comment by chylex** [comment]
Try replicating it without any other mods.

**Comment by Ianaver** [comment]
sorry for the inconvenience, it was a corrupted world save :) there are 2 problems still there, I will open separate issues for those.
