### ISSUE TITLE
Music issue

### ISSUE THREAD

**Issue by Ianaver** [chylex/Hardcore-Ender-Expansion#92]
The background music tends to take a while to start or (rarely) never does, if it does start it has a tendency to change, stop or restart in the middle of another track. Again this issue is just a minor inconvenience, but it would be nice to have fixed if possible.

**Comment by chylex** [comment]
Say hi to Mojang, because they completely rewrote the music code in 1.7 and that's how the game's music works now...

**Comment by Ianaver** [comment]
oh... so do I need to close this one or what?

**Comment by chylex** [comment]
I might be able to work around it, I had to overwrite the entire stupid thing so I might as well try to fix it.

**Comment by chylex** [comment]
Fixed.
