### ISSUE TITLE
[FIXED 1.8] Enderdragon unloads when it gets far away

### ISSUE THREAD

**Issue by Ianaver** [chylex/Hardcore-Ender-Expansion#93]
The enderdragon sometimes flies too far and despawns untill you come to it. When it does despawn, its health bar also disappears

**Comment by chylex** [comment]
It doesn't despawn, it gets unloaded; it's really annoying, but I don't know what I could do with it, apart from making it an entity chunkloader, for which I need some documentation because I've no idea what I've done wrong the last time I tried it.

**Comment by chylex** [comment]
Figured out the chunkloading thing, the dragon will keep 3x3 chunk area alive until you kill it.
