### ISSUE TITLE
Press 'NONE' to open Ender Compendium

### ISSUE THREAD

**Issue by skaviouz** [chylex/Hardcore-Ender-Expansion#99]
#### Premise:
If a player set the key to 'NONE' that means at the moment, that player isn't going to be using the menu for HEE.

#### Idea:
Wouldn't it make sense to just hide the text (not giving credit for opening menu of coarse), until the player resets the key/change, thus reminding the player to use and learn about HEE?

![example image of the message I am talking about](https://i.imgur.com/Ksy37BF.jpg)

Image is from the courtesy of plazia.

**Comment by chylex** [comment]
I was not aware that you can unbind keys... it uses the same system as inventory key achievement, except I made it so it disappears after a couple seconds if you ignore it. Not exactly sure what you want me to do with that, can you explain it in further detail please?

**Comment by plazia** [comment]
This is actually a screenshot he stole from me ;) The key point being though that the notification in the top right didn't disappear after several minutes.

**Comment by chylex** [comment]
Disappear time is set to about 8 seconds, I test this one often because of the way my workspace is setup... The notification disappears in a couple seconds just fine, if you have any details on how to replicate the issue, then let me know.

**Comment by skaviouz** [comment]
When you are setting a keybind, and it's waiting for a key, press ESC for "NONE".

**Comment by chylex** [comment]
Though you removed the comment, thanks for the info :P it should not have any relation to the notification not disappearing whatsoever, you probably have an old version or something.
